SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `__PREFIX__cache`;
CREATE TABLE `__PREFIX__cache` (
  `cache_id` varchar(255) NOT NULL,
  `cache_value` mediumtext NOT NULL,
  `cache_manual` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`cache_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='qEngine Cache';


DROP TABLE IF EXISTS `__PREFIX__config`;
CREATE TABLE `__PREFIX__config` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `group_id` varchar(255) NOT NULL,
  `config_id` varchar(255) NOT NULL DEFAULT '',
  `config_value` varchar(255) NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `config_id` (`config_id`),
  KEY `group_id` (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='qEngine Configuration';

INSERT INTO `__PREFIX__config` (`idx`, `group_id`, `config_id`, `config_value`) VALUES
(1, '', 'site_url', ''),
(2, '', 'abs_path', ''),
(3, '', 'site_name',  'Demo Site'),
(4, '', 'site_slogan',  'Be Unique. Be Different.'),
(5, '', 'site_description', 'Another site powered by qEngine'),
(6, '', 'site_keywords',  'qengine,cms,c97'),
(7, '', 'site_email', 'admin@admin.com'),
(8, '', 'site_mobile',  'N/A'),
(9, '', 'num_decimals', '2'),
(10,  '', 'num_dec_point',  '.'),
(11,  '', 'num_thousands_sep',  ','),
(12,  '', 'num_currency', '$'),
(13,  '', 'num_curr_pos', '0'),
(14,  '', 'enable_gzip',  '0'),
(15,  '', 'adp_extension',  'php'),
(16,  '', 'enable_adp', '0'),
(17,  '', 'skin', 'skins/default'),
(18,  '', 'list_ipp', '20'),
(19,  '', 'wysiwyg',  '1'),
(20,  '', 'gd_library', '2'),
(21,  '', 'thumb_size', '250'),
(22,  '', 'thumb_quality',  '80'),
(23,  '', 'optimizer',  '80'),
(24,  '', 'multi_lang', '0'),
(25,  '', 'site_start', ''),
(26,  '', 'last_autoexec',  ''),
(27,  '', 'site_fax', '555-123'),
(28,  '', 'site_phone', '555-321'),
(29,  '', 'site_country', 'United States'),
(30,  '', 'site_state', 'Somewhere'),
(31,  '', 'close_site', '0'),
(32,  '', 'weight_name',  'kg'),
(33,  '', 'bbcode', ''),
(34,  '', 'site_address', 'Somestreet No 97'),
(35,  '', 'site_address2',  ''),
(36,  '', 'site_city',  'Somecity'),
(37,  '', 'site_zip', '90210'),
(38,  '', 'user_activation',  '0'),
(39,  '', 'mailog', '1'),
(40,  '', 'num_curr_name',  'USD'),
(41,  '', 'qe_version', '16.2.0/20170924'),
(42,  '', 'company_logo', 'somecompanylogo.png'),
(43,  '', 'favicon',  'somefavicon.png'),
(44,  '', 'cache',  '3600'),
(45,  '', 'allowed_file', 'jpg,jpeg,bmp,gif,png,pcx,zip,7z,doc,xls,ppt,txt,ico,pdf,mp3'),
(46,  '', 'debug_mode', '0'),
(47,  '', 'disable_browser_cache',  '0'),
(48,  '', 'smtp_email', '0'),
(49,  '', 'smtp_secure',  'ssl'),
(50,  '', 'smtp_server',  'smtp.example.com'),
(51,  '', 'smtp_port',  '465'),
(52,  '', 'smtp_user',  'mymail@example.com'),
(53,  '', 'smtp_passwd',  'mypwd'),
(54,  '', 'smtp_sender',  'mymail@example.com'),
(55,  '', 'enable_module_engine', '1'),
(56,  '', 'enable_module_man',  '1'),
(57,  '', 'enable_qadmin_log',  '1'),
(58,  '', 'enable_detailed_log',  '0'),
(59,  '', 'mobile_version', '0'),
(60,  '', 'default_lang', 'en'),
(61,  '', 'cat_separator',  '&bull;'),
(62,  '', 'facebook_like',  '1'),
(63,  '', 'facebook_comment', '0'),
(64,  '', 'twitter_share',  '1'),
(65,  '', 'allow_locked_page_list', '1'),
(66,  '', 'watermark_file', ''),
(67,  '', 'watermark_position', 'BR'),
(68,  '', 'gmap_api', ''),
(69,  'mod_qstats', 'stats_last_update',  ''),
(70,  'permisi',  'manage_module',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(71,  'permisi',  'page_download',  'a:6:{i:0;s:1:\"1\";i:1;s:1:\"1\";i:2;s:1:\"1\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(72,  'permisi',  'page_editor',  'a:6:{i:0;s:0:\"\";i:1;s:1:\"1\";i:2;s:1:\"1\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(73,  'permisi',  'site_config',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:0:\"\";i:4;s:0:\"\";i:5;s:1:\"1\";}'),
(74,  'permisi',  'manage_user',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(75,  'permisi',  'manage_menu',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(76,  'permisi',  'site_setting', 'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:0:\"\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(77,  'permisi',  'permisi',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:0:\"\";i:4;s:0:\"\";i:5;s:1:\"1\";}'),
(78,  'permisi',  'page_manager', 'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:1:\"1\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(79,  'permisi',  'site_log', 'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:0:\"\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(80,  'permisi',  'site_file',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:0:\"\";i:4;s:1:\"1\";i:5;s:1:\"1\";}');


DROP TABLE IF EXISTS `__PREFIX__ip_log`;
CREATE TABLE `__PREFIX__ip_log` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `log_time` int(10) unsigned NOT NULL DEFAULT '0',
  `log_ip_addr` varchar(45) NOT NULL DEFAULT '',
  `log_user_id` varchar(80) NOT NULL DEFAULT '',
  `log_user_type` char(1) NOT NULL DEFAULT 'U',
  `log_success` char(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idx`),
  KEY `log_user_type` (`log_user_type`),
  KEY `log_ip_addr` (`log_ip_addr`),
  KEY `log_user_id` (`log_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__language`;
CREATE TABLE `__PREFIX__language` (
  `lang_id` char(2) NOT NULL,
  `lang_key` varchar(255) NOT NULL,
  `lang_value` text NOT NULL,
  KEY `lang_id` (`lang_id`),
  KEY `lang_key` (`lang_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__language` (`lang_id`, `lang_key`, `lang_value`) VALUES
('en',  'datetime.Apr', 'Apr'),
('en',  'datetime.April', 'April'),
('en',  'datetime.Aug', 'Aug'),
('en',  'datetime.August',  'August'),
('en',  'datetime.Dec', 'Dec'),
('en',  'datetime.December',  'December'),
('en',  'datetime.Feb', 'Feb'),
('en',  'datetime.February',  'February'),
('en',  'datetime.Fri', 'Fri'),
('en',  'datetime.Friday',  'Friday'),
('en',  'datetime.Jan', 'Jan'),
('en',  'datetime.January', 'January'),
('en',  'datetime.Jul', 'Jul'),
('en',  'datetime.July',  'July'),
('en',  'datetime.Jun', 'Jun'),
('en',  'datetime.June',  'June'),
('en',  'datetime.Mar', 'Mar'),
('en',  'datetime.March', 'March'),
('en',  'datetime.May', 'May'),
('en',  'datetime.Mon', 'Mon'),
('en',  'datetime.Monday',  'Monday'),
('en',  'datetime.Nov', 'Nov'),
('en',  'datetime.November',  'November'),
('en',  'datetime.Oct', 'Oct'),
('en',  'datetime.October', 'October'),
('en',  'datetime.Sat', 'Sat'),
('en',  'datetime.Saturday',  'Saturday'),
('en',  'datetime.Sep', 'Sep'),
('en',  'datetime.September', 'September'),
('en',  'datetime.Sun', 'Sun'),
('en',  'datetime.Sunday',  'Sunday'),
('en',  'datetime.Thu', 'Thu'),
('en',  'datetime.Thursday',  'Thursday'),
('en',  'datetime.Tue', 'Tue'),
('en',  'datetime.Tuesday', 'Tuesday'),
('en',  'datetime.Wed', 'Wed'),
('en',  'datetime.Wednesday', 'Wednesday'),
('en',  'l_account',  'Account'),
('en',  'l_account_act',  'Account Activation'),
('en',  'l_account_act_key',  'Activation Key'),
('en',  'l_account_act_key_why',  'You will find the key, in the email we sent to you.'),
('en',  'l_account_act_why',  'All new members must activate their account before logging in.'),
('en',  'l_admin_level_1',  'Staffs'),
('en',  'l_admin_level_2',  'Supervisors'),
('en',  'l_admin_level_3',  'Managers'),
('en',  'l_admin_level_4',  'Administrators'),
('en',  'l_admin_level_5',  'Owners'),
('en',  'l_all',  'All'),
('en',  'l_all_cat',  'All Categories'),
('en',  'l_all_news', 'All News'),
('en',  'l_article_by', 'Articles by'),
('en',  'l_back', 'Back'),
('en',  'l_bottom', 'Bottom'),
('en',  'l_browser_back_button',  'Please use your browser <a href=\"javascript:history.go(-1)\">&lt;back&gt;</a> button to return to previous page!'),
('en',  'l_captcha_error',  'Invalid Captcha'),
('en',  'l_comment',  'Comments'),
('en',  'l_comment_helpful',  '%1$s of %2$s people found this comment to be helpful'),
('en',  'l_conc_non', 'Reply to this'),
('en',  'l_conc_num', 'There are %1$s replies to this comment'),
('en',  'l_confirm_password', 'Confirm New Password'),
('en',  'l_contact_us', 'Contact Us'),
('en',  'l_contact_us_form',  'Fill in this form to send us a message.'),
('en',  'l_contents', 'Contents'),
('en',  'l_content_search', 'Content Search'),
('en',  'l_current_password', 'Current Password'),
('en',  'l_date', 'Date'),
('en',  'l_default',  'Default'),
('en',  'l_demo_mode',  '<p align=\"center\">Demo mode, you can\'t upload files in demo mode!</p>'),
('en',  'l_direction',  'ltr'),
('en',  'l_down', 'Down'),
('en',  'l_downloaded', 'downloaded'),
('en',  'l_downloading',  'Downloading'),
('en',  'l_download_click', 'Click the link if download does not start automatically.'),
('en',  'l_edit', 'Edit'),
('en',  'l_email_address',  'Email Address'),
('en',  'l_email_error',  'Invalid email'),
('en',  'l_email_used', 'Please choose a different email address'),
('en',  'l_encoding', 'utf-8'),
('en',  'l_enter_captcha',  'Type the characters into the box:'),
('en',  'l_enter_page_number',  'Enter page number'),
('en',  'l_facebook_comment', 'Facebook Comments'),
('en',  'l_friend_email', 'Friend\'s Email'),
('en',  'l_friend_name',  'Friend\'s Name'),
('en',  'l_guest',  'Guest'),
('en',  'l_item', 'item'),
('en',  'l_items',  'items'),
('en',  'l_language_short', 'en-us'),
('en',  'l_last_updated', 'Last Updated'),
('en',  'l_left', 'Left'),
('en',  'l_login',  'Login'),
('en',  'l_login_register', 'Login/Register'),
('en',  'l_login_why',  'Enter your username &amp; password to log in.'),
('en',  'l_logout', 'Log Out'),
('en',  'l_long_date_format', 'l, F-d-Y'),
('en',  'l_lost_passwd',  'Lost Password'),
('en',  'l_mail_friend_subject',  'Your friend wanted to show you a website that you might be interested in'),
('en',  'l_mail_lost_subject',  'Your password at %1$s'),
('en',  'l_mail_register',  'Your account at %1$s'),
('en',  'l_mail_us_subject',  'Subject'),
('en',  'l_manage_faq', 'Knowledge Center/FAQ'),
('en',  'l_manage_faq_why', 'Do you have a problem or question? Please visit our knowledge center and if you still cannot find an answer, you can also contact us.'),
('en',  'l_manage_logout_why',  'Logout from your account. It\'s highly recommended to logout after each transaction, especially on a public computer.'),
('en',  'l_manage_profile', 'Manage Profile'),
('en',  'l_manage_profile_why', 'Manage your email &amp; password.'),
('en',  'l_manage_subscription',  'Manage Subscription'),
('en',  'l_manage_subscription_why',  'Manage your subscription to our newsletter, email reminders and more.'),
('en',  'l_message',  'Message'),
('en',  'l_message_empty',  'No message was entered'),
('en',  'l_more_comment', 'There are %1$s comments. Why not add your own?'),
('en',  'l_more_result',  'More Results'),
('en',  'l_mysql_encoding', 'utf8'),
('en',  'l_my_account', 'My Account'),
('en',  'l_name_empty', 'Please give us your name'),
('en',  'l_na_select',  'n/a'),
('en',  'l_never',  'Never'),
('en',  'l_newsletter', 'Newsletter'),
('en',  'l_newsletter_subscribed',  'You are currently subscribed to our newsletter'),
('en',  'l_newsletter_unsubscribed',  'You are currently not subscribed to our newsletter'),
('en',  'l_new_password', 'New Password'),
('en',  'l_no', 'No'),
('en',  'l_none', 'None'),
('en',  'l_no_comment', 'There is no comment. Why not be the first?'),
('en',  'l_no_description', 'No description.'),
('en',  'l_ok', 'Ok'),
('en',  'l_one_comment',  'There is one comment. Why not be the second?'),
('en',  'l_open_url', '<a href=\"%1$s\"><img src=\"../skins/_admin/images/url.gif\" border=\"0\" alt=\"Open Link\" /> %2$s</a>'),
('en',  'l_other_cat',  'Other Categories'),
('en',  'l_page', 'page'),
('en',  'l_pages',  'pages'),
('en',  'l_page_admin_only',  '<h1>This page is only available to administrators, please login to read this page!</h1>'),
('en',  'l_page_author',  'Author'),
('en',  'l_page_draft', '<h1 class=\"well\">This page has not been published, yet!</h1>'),
('en',  'l_page_gallery', 'Gallery'),
('en',  'l_page_member_only', '<h1>This page is only available to members, please register/login, in order to read this page!</h1>'),
('en',  'l_page_not_found', '<h1>Page not found!</h1>'),
('en',  'l_passwd_changed_subject', 'Your password has been changed!'),
('en',  'l_passwd_not_entered', 'Password not entered'),
('en',  'l_password', 'Password'),
('en',  'l_password_empty', 'Incorrect password'),
('en',  'l_password_error', 'Password Error!'),
('en',  'l_posted_by',  'Posted By'),
('en',  'l_posted_on',  'Posted On'),
('en',  'l_pp_last',  'Last'),
('en',  'l_pp_next',  '&raquo;'),
('en',  'l_pp_prev',  '&laquo;'),
('en',  'l_pp_top', 'First'),
('en',  'l_print',  'Print This Page'),
('en',  'l_profile_enter_passwd', 'Enter your current password, in order to change your password or email address'),
('en',  'l_quick_search', 'Search in title only (quick search)'),
('en',  'l_rating_1', 'Poor'),
('en',  'l_rating_2', 'Below Average'),
('en',  'l_rating_3', 'Average'),
('en',  'l_rating_4', 'Above Average'),
('en',  'l_rating_5', 'Excellent'),
('en',  'l_register', 'Register'),
('en',  'l_register_now', 'Register Now'),
('en',  'l_related_page', 'Related Pages'),
('en',  'l_reset_code', 'Reset Code'),
('en',  'l_reset_passwd', 'Reset Password'),
('en',  'l_right',  'Right'),
('en',  'l_search', 'Search'),
('en',  'l_search_no_result', 'Sorry, we could not find what your were looking for. Please try refining your search terms, or contact us for assistance.'),
('en',  'l_search_result',  'Search Results'),
('en',  'l_select_date_format', 'MDY'),
('en',  'l_short_date_format',  'M-d-Y'),
('en',  'l_sitemap',  'Sitemap'),
('en',  'l_site_closed_info', '<h1>Site Closed</h1><p>Thank you for coming to our website. It has been temporarily closed while we are updating it. Please come back again soon.</p><p>The website administrator can login to see the web site.</p>'),
('en',  'l_site_news',  'Site Announcements'),
('en',  'l_site_search',  'Site Search'),
('en',  'l_subject',  'Subject'),
('en',  'l_submit', 'Submit'),
('en',  'l_subscribe',  'Subscribe'),
('en',  'l_subscribe_newsletter', 'Subscribe to our free newsletter'),
('en',  'l_tell_friend',  'Share this site'),
('en',  'l_title',  'Title'),
('en',  'l_top',  'Top'),
('en',  'l_unsubscribe',  'Unsubscribe'),
('en',  'l_untitled', 'Untitled'),
('en',  'l_up', 'Up'),
('en',  'l_username', 'Username'),
('en',  'l_username_error', 'Invalid username'),
('en',  'l_username_used',  'In use! Please choose another username'),
('en',  'l_user_level_1', 'Bronze'),
('en',  'l_user_level_2', 'Silver'),
('en',  'l_user_level_3', 'Gold'),
('en',  'l_user_level_4', 'Platinum'),
('en',  'l_user_level_5', 'Diamond'),
('en',  'l_yes',  'Yes'),
('en',  'l_your_email', 'Your Email'),
('en',  'l_your_name',  'Your Name'),
('en',  'l_you_are_here', 'You are here'),
('en',  'l_you_are_login',  'You are logged in as'),
('en',  'l_you_are_not_login',  'You are not logged in.'),
('en',  'mail.admin_mail',  '<p><b>Hello {$user_id},</b></p>\r\n\r\n<p>[write your message here]</p>'),
('en',  'mail.change_pwd',  '<p>Hi, {$user_id}<br />\r\nToday, you or someone else has changed your password to:<br />\r\n<b>{$user_passwd}</b></p>\r\n\r\n<p>If you didn\'t make this change, please login to your account immediately, using the above information, and contact us for more information.</p>\r\n\r\n<p>Thank you,<br />\r\n<br />\r\n{$site_name}</p>'),
('en',  'mail.contact', '<p>You have been sent a message from your website {$l_site_name}.</p>\r\n<hr />\r\n<p>Name: {$name}<br />\r\nEmail: {$email}</p>\r\n\r\n<p>The message:</p>\r\n{$body}'),
('en',  'mail.contact_reply', '<p>Thank you for contacting us, {$name}.</p>\r\n\r\n<p>We will respond to your enquiry as soon a possible. In the meantime, please visit our website for more information.</p>\r\n\r\n<p>Best regards,<br />\r\n{$title}</p>'),
('en',  'mail.lost',  '<p>Hi,<br />\r\nyou have requested to reset your password at {$site_name}.</p>\r\n\r\n<p>Your username: {$user_id}<br />\r\nYour reset code: {$reset}</p>\r\n\r\n<p>All you have to do is go to\r\n<a href=\"\"{$site_url}/profile.php?mode=reset&user_id={$user_id}&reset={$reset}\"\">{$site_url}/profile.php?mode=reset&user_id={$user_id}&reset={$reset}</a>\r\nand you can enter your new password.</p>\r\n\r\n<p>Thank you.</p>'),
('en',  'mail.newsletter',  '<p>ENTER YOUR MESSAGE HERE</p>'),
('en',  'mail.outline', '<!DOCTYPE html>\r\n<html lang=\"\"en\"\">\r\n<head>\r\n  <meta charset=\"\"{$l_encoding}\"\" />\r\n  <meta name=\"\"description\"\" content=\"\"{$site_description}\"\" />\r\n <meta name=\"\"keywords\"\" content=\"\"{$site_keywords}\"\" />\r\n <meta name=\"\"author\"\" content=\"\"{$site_email}\"\" />\r\n  <base href=\"\"{$site_url}/\"\" />\r\n  <style type=\"\"text/css\"\">\r\n body{background:#eee}\r\n th{text-align:left}\r\n *{font-family:Arial,Helvetica,San-serif}\r\n  </style>\r\n</head>\r\n\r\n<body>\r\n <div style=\"\"max-width:700px;margin:auto\"\">\r\n   <div>{$company_logo}</div>\r\n    <div style=\"\"border-top:solid 10px #333; background:#fff; padding:20px\"\">\r\n   <<main_body>>\r\n   </div>\r\n    <div style=\"\"color:#888;font-size:8pt\"\">\r\n      &copy; {$site_name} &mdash; <a href=\"\"{$site_url}\"\">{$site_url}</a>, Email: <a href=\"\"mailto:{$site_email}\"\">{$site_email}</a>\r\n    </div>\r\n</body>\r\n</html>'),
('en',  'mail.register',  '<p>You are now registered at {$site_name} (<a href=\"\"{$site_url}\"\">{$site_url}</a>)</p>\r\n\r\n<p>This email contains your username & password</p>\r\n\r\n<p>Email: {$user_email}<br />\r\n Username: {$user_id}<br />\r\n Password: {$user_passwd}<br />\r\n<!-- BEGINIF $act -->\r\n Activation Code: {$act}</p>\r\n\r\n<p>Our site requires you to activate your account before you can login.</p>\r\n<p>To activate your account, simply go to: <a href=\"\"{$site_url}/profile.php?mode=act&user_id={$user_id}&act={$act}\"\">{$site_url}/profile.php?mode=act&user_id={$user_id}&act={$act}</a>\r\n<!-- ENDIF -->\r\n</p>\r\n\r\n<p>Best Regards,<br />\r\n{$site_url}\r\n\r\n<p>If you have never registered at {$site_name}, please contact us.</p>'),
('en',  'mail.tell',  '<p>Hi, {$friend_name},</p>\r\n<p>Your friend, {$name} (email: {$email}) thinks you might be interested in our site.<br />\r\nFor more information, please visit <a href=\"\"{$site_url}\"\">{$site_name}</a>.</p>\r\n\r\n<p>Additionally, your friend says:<br />\r\n{$tell_body}</p>\r\n\r\n<p>Best Regards,<br />\r\n{$site_name}</p>'),
('en',  'msg.act_error',  '<h1>Activation Failed!</h1>\r\n<p>%1$s</p>'),
('en',  'msg.admin_err',  '<h1>FAILED!</h1>\r\n<p>Something is wrong. Make sure that you have filled all required fields, and try again.</p>'),
('en',  'msg.admin_error',  '<h1>FAILED!</h1>\r\n<p>Something is wrong. Make sure that you have filled all required fields, and try again.</p>'),
('en',  'msg.admin_ok', '<h1>Complete!</h1>\r\n<p>Your changes have been saved</p>'),
('en',  'msg.bad_login',  '<h1>Unable to Login!</h1>\r\n<p>Incorrect username or password. Please try again or contact us for assistance</p>'),
('en',  'msg.cache',  '<h1>Please Rebuild System Cache</h1>\r\n<p>If you have made some changes, then you should <a href=\"\"cache.php\"\"> rebuild your system cache</a>. This makes your site run more efficiently.</p>'),
('en',  'msg.can_not_upload', '<h1>Not Allowed!</h1>\r\n<p>You are trying to upload restricted files, or site in demo mode. Upload has been cancelled!</p>'),
('en',  'msg.captcha_error',  '<h1>Invalid Captcha!</h1>\r\n<p>Please enter the number shown on screen correctly!</p>'),
('en',  'msg.contact_err',  '<h1>Can not send the information</h1>\r\n<p>This is why: %1$s</p>'),
('en',  'msg.contact_ok', '<h1>Complete</h1>\r\n<p>Your message has been sent. Thank you.</p>'),
('en',  'msg.default',  '<h1>For your Attention...</h1>\r\n<p>Message ID: %1$s<br /><a href=\"\"mailto:\"\">Contact C97net</a> (www.c97.net) for more information</p>'),
('en',  'msg.demo_mode',  '<h1>Demo Mode!</h1>\r\n<p>Currently running in demo mode.<br />Your changes have not been saved!</p>'),
('en',  'msg.echo', '<h1>Notice!</h1>\r\n<p>%1$s</p>'),
('en',  'msg.email_err',  '<h1>Invalid Email Address!</h1>\r\n<p>The email address you just entered does not appear to be valid. Please ensure you have entered it correctly or enter an alternative email address</p>'),
('en',  'msg.email_ok', '<h1>Email Sent!</h1>\r\n<p>An email has been sent to the recipient.</p>'),
('en',  'msg.ezform_ok',  '<h1>Form Has Been Submitted!</h1>\r\n<p>Thank you!</p>'),
('en',  'msg.ezform_required_err',  '<h1>Form Cannot Be Submitted!</h1>\r\n<p>%1$s</p>'),
('en',  'msg.fman_copy_err',  '<h1>File Manager Error</h1>\r\n<p>File copy failed!</p>'),
('en',  'msg.fman_del_err', '<h1>File Manager Error</h1>\r\n<p>File deletion failed!</p>'),
('en',  'msg.fman_error', '<h1>File Manager Error</h1>\r\n<p>Cannot proceed with this request. Please make sure that you have enough privileges.</p>'),
('en',  'msg.fman_mkdir_err', '<h1>File Manager Error</h1>\r\n<p>Make new folder failed!</p>'),
('en',  'msg.fman_move_err',  '<h1>File Manager Error</h1>\r\n<p>File move failed!</p>'),
('en',  'msg.fman_new_err', '<h1>File Manager Error</h1>\r\n<p>File creation failed</p>'),
('en',  'msg.fman_not_allowed', '<h1>File Manager Error</h1>\r\n<p>You are not allowed to do this!</p>'),
('en',  'msg.fman_not_found', '<h1>File Manager Error</h1>\r\n<p>File not found!</p>'),
('en',  'msg.fman_rendir_err',  '<h1>File Manager Error</h1>\r\n<p>Folder rename failed</p>'),
('en',  'msg.fman_ren_err', '<h1>File Manager Error</h1>\r\n<p>File rename failed!</p>'),
('en',  'msg.fman_rmdir_err', '<h1>File Manager Error</h1>\r\n<p>Folder deletion failed</p>'),
('en',  'msg.lost_error', '<h1>Password Retrieval Failed!</h1>\r\n<p>Your username/email address could not be found in our database.</p>'),
('en',  'msg.lost_ok',  '<h1>Password Retrieval Success!</h1>\r\n<p>An email has been sent to you containing information regarding your username &amp; password. Please check your inbox.</p>'),
('en',  'msg.menuman_locked_err', '<h1>Menu Manager Error</h1>\r\n<p>This menu is locked by another application. Please use the application to edit this menu!</p>'),
('en',  'msg.module_engine_disabled', '<h1>Module Error!</h1>\r\n<p>MODULE_ENGINE is disabled!</p>'),
('en',  'msg.module_engine_error',  '<h1>Module Error!</h1>\r\n<p>Module <b>%1$s</b> is disabled or not installed!</p>'),
('en',  'msg.mod_installed',  '<h1>Installation Failed</h1>\r\n<p>This module has not been installed.</p>'),
('en',  'msg.mod_install_ok', '<h1>Installation Complete</h1>\r\n<p>You may need to <a href=\"\"#\"\" onclick=\"\"top.location.reload(true)\"\">refresh your browser</a> to display the new module menu.</p>'),
('en',  'msg.mod_not_installed',  '<h1>Uninstallation Failed</h1>\r\n<p>This module has not been installed.</p>'),
('en',  'msg.mod_uninstall_ok', '<h1>Uninstalled</h1>\r\n<p>You may need to <a href=\"\"#\"\" onclick=\"\"top.location.reload(true)\"\">refresh browser</a> to remove module menu.<br />You may also need to remove some files/folders manually.</p>'),
('en',  'msg.msg_about',  '<h1>Copyright(c)C97net</h1>\r\n<p>This software is powered by <a href=\"\"http://www.c97.net\"\">qEngine</a>Removal of this copyright information or any other credits is strictly prohibited</p>'),
('en',  'msg.not_member', '<h1>Members Only!</h1>\r\n<p>This page is for members only! Please login first!</p>'),
('en',  'msg.no_cat_list',  '<h1>Not Allowed!</h1>\r\n<p>You are not allowed to see the page list!</p>'),
('en',  'msg.no_config',  '<h1>No Configurable Options</h1>\r\n<p>This module/plugin has no options that you can configure.</p>'),
('en',  'msg.no_level', '<h1>You Don\'t Have Permission!</h1>\r\n<p>This feature requires that you have a higher administrator level.</p>'),
('en',  'msg.ok', '<h1>Complete!</h1>\r\n<p>Your changes have been saved</p>'),
('en',  'msg.page_attachment_error',  '<h1>Download Failed!</h1>\r\n<p>Attachment is either not available or not found!</p>'),
('en',  'msg.passwd_changed', '<h1>Password Changed!</h1>\r\n<p>Your password has been changed. You may need to logout of your account and login again.</p>'),
('en',  'msg.permalink_cfg_error',  '<h1>Fatal Error</h1>\r\n<p>Permalink setting is invalid! See qadmin_demo!</p>'),
('en',  'msg.permalink_error',  '<h1>Page Not Found</h1>\r\n<p>Document %1$s not found. Please contact us for more information.</p>'),
('en',  'msg.qadmin_email_ok',  '<h1>Complete!</h1>\r\n<p>Your changes have been saved. An email has also been sent to your address with form values.</p>'),
('en',  'msg.qadmin_item_not_found',  '<h1>Fatal Error</h1>\r\n<p>Item not found!</p>'),
('en',  'msg.qadmin_required_err',  '<h1>Empty Fields!</h1>\r\n<p>Please fill the following: %1$s</p>'),
('en',  'msg.qcomment_err_1', '<h1>Comment Error!</h1>\r\n<p>Invalid mod_id, please define it in ACP!</p>'),
('en',  'msg.qcomment_err_2', '<h1>Comment Error!</h1>\r\n<p>Invalid page title!</p>'),
('en',  'msg.qcomment_err_3', '<h1>Comment Error!</h1>\r\n<p>You can only comment once for the same item!</p>'),
('en',  'msg.qcomment_err_4', '<h1>Comment Error!</h1>\r\n<p>Please enter a message!</p>'),
('en',  'msg.qcomment_err_5', '<h1>Comment Error!</h1>\r\n<p>You have voted for this item!</p>'),
('en',  'msg.qcomment_err_6', '<h1>Comment Error!</h1>\r\n<p>Invalid rating value!</p>'),
('en',  'msg.qcomment_ok_1',  '<h1>Comment accepted</h1>\r\n<p>We will post it as soon as possible. Thank your for your participation!</p>'),
('en',  'msg.qcomment_ok_2',  '<h1>Vote accepted</h1>\r\n<p>We will post it as soon as possible. Thank your for your participation!</p>'),
('en',  'msg.register_error', '<h1>Register Error!</h1>\r\n<p>Error in: %1$s</p>'),
('en',  'msg.register_ok',  '<h1>Congratulation!</h1>\r\n<p>You have been registered in this site successfully!<br />Please enjoy your stay!</p>'),
('en',  'msg.reset_error',  '<h1>Password Reset Failed!</h1>\r\n<p>Make sure you have entered valid username, reset code and new password!</p>'),
('en',  'msg.sa_only',  '<h1>Whoops!</h1>\r\n<p>This feature is for administrators only!</p>'),
('en',  'msg.site_closed',  '<h1>Temporarily Closed!</h1>\r\n<p>%1$s is temporarily closed as we are updating our site.<br />Please try visiting us again soon!.</p>'),
('en',  'msg.sql_error',  '<h1>Database Error</h1>\r\n<p>%1$s</p>'),
('en',  'msg.ssl_error',  '<h1>SSL ERROR!</h1>\r\n<p>Your server does not support SSL connection. Please review your configuration</p>'),
('en',  'msg.sub_ok', '<h1>Subscription Success!</h1>\r\n<p>Thanks for subscribing to our site. Check your inbox soon for notifications from us.</p>'),
('en',  'msg.tell_error', '<h1>Whoops!</h1>\r\n<p>It looks like you missed entering some of the information that was required. Please try again.</p>'),
('en',  'msg.tell_ok',  '<h1>Complete</h1>\r\n<p>An email has been sent to %1$s Thank you.</p>'),
('en',  'msg.tpl_only', '<h1>Cannot Open File!</h1>\r\n<p>You are about to open a file that is not a recognized skin-file. (*.tpl) files are skin files and are used to make your site look as it does.</p>'),
('en',  'msg.unsub_ok', '<h1>Subscription Changes Made!</h1>\r\n<p>Your email address has now been removed from our database and you will not receive any more correspondence from us.</p>'),
('en',  'msg.update_error', '<h1>Profile Error!</h1>\r\n<p>Error in: %1$s</p>'),
('en',  'msg.username_not_found', '<h1>Username Not Available!</h1>\r\n<p>Username can not be found or is no longer available!</p>'),
('en',  'msg.user_act', '<h1>User Activation Required!</h1>\r\n<p>We require all new members to activate their account before they can login.<br />Please check your emails for more information and to verify your email address</p>'),
('en',  '_config:cache',  ''),
('en',  '_config:enabled',  '1'),
('en',  '_config:lang_name',  'English');


DROP TABLE IF EXISTS `__PREFIX__mailog`;
CREATE TABLE `__PREFIX__mailog` (
  `log_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `log_address` varchar(255) NOT NULL DEFAULT '',
  `log_subject` varchar(255) NOT NULL DEFAULT '',
  `log_body` text NOT NULL,
  `log_time` int(10) unsigned NOT NULL DEFAULT '0',
  `log_html` char(1) NOT NULL DEFAULT '',
  PRIMARY KEY (`log_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__menu_item`;
CREATE TABLE `__PREFIX__menu_item` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `menu_id` int(10) unsigned NOT NULL,
  `menu_parent` int(10) unsigned NOT NULL,
  `menu_item` varchar(255) NOT NULL,
  `menu_url` varchar(255) NOT NULL,
  `menu_permalink` varchar(255) NOT NULL,
  `menu_order` int(10) unsigned NOT NULL,
  `ref_idx` int(10) unsigned NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `menu_id` (`menu_id`),
  KEY `ref_idx` (`ref_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__menu_item` (`idx`, `menu_id`, `menu_parent`, `menu_item`, `menu_url`, `menu_permalink`, `menu_order`, `ref_idx`) VALUES
(1, 1,  0,  'Home', '__SITE__/index.php', '', 100,  0),
(2, 1,  0,  'About Us', '4',  '', 110,  0),
(3, 1,  0,  'Contact Us', '__SITE__/contact.php', '', 140,  0),
(4, 2,  0,  'Contact Us', '__SITE__/contact.php', '', 100,  0),
(5, 2,  0,  'Site Map', '__SITE__/sitemap.php', '', 110,  0),
(7, 2,  0,  'Tell a Friend',  '__SITE__/tell.php',  '', 120,  0),
(8, 3,  0,  'Privacy Policy', '2',  '', 100,  0),
(9, 3,  0,  'Terms &amp; Conditions', '7',  '', 110,  0),
(10,  3,  0,  'Powered by qEngine', '8',  '', 130,  0),
(11,  3,  0,  'FAQ',  '3',  '', 120,  0);

DROP TABLE IF EXISTS `__PREFIX__menu_set`;
CREATE TABLE `__PREFIX__menu_set` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `menu_id` varchar(255) NOT NULL,
  `menu_title` varchar(255) NOT NULL,
  `menu_preset` varchar(255) NOT NULL,
  `menu_class` varchar(255) NOT NULL,
  `menu_notes` text NOT NULL,
  `menu_cache` text NOT NULL,
  `menu_locked` enum('0','1') NOT NULL DEFAULT '0',
  `max_depth` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `ref_idx` int(10) unsigned NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `ref_idx` (`ref_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__menu_set` (`idx`, `menu_id`, `menu_title`, `menu_preset`, `menu_class`, `menu_notes`, `menu_cache`, `menu_locked`, `ref_idx`) VALUES
(1, 'main_menu',  'Main Menu',  'bsnav',  '', 'Main menu, usually located at the top of the page.', '<ul id=\"qmenu_main_menu\" class=\"nav navbar-nav\">\n <li><a href=\"__SITE__/index.php\">Home</a></li>\n <li><a href=\"__SITE__/page.php?pid=4\">About Us</a></li>\n  <li><a href=\"__SITE__/contact.php\">Contact Us</a></li>\n</ul>\n', '0',  0),
(2, 'footer_menu',  'Footer Menu',  'list_1', '', 'Footer menu, usually located at the end of the page.', '<ul id=\"qmenu_footer_menu\" class=\"list_1\">\n <li><a href=\"__SITE__/contact.php\">Contact Us</a></li>\n  <li><a href=\"__SITE__/sitemap.php\">Site Map</a></li>\n  <li><a href=\"__SITE__/tell.php\">Tell a Friend</a></li>\n</ul>\n', '0',  0),
(3, 'page_menu',  'Page Menu',  'list_1', '', 'Menu linking to some important, but not that important pages.',  '<ul id=\"qmenu_page_menu\" class=\"list_1\">\n <li><a href=\"__SITE__/page.php?pid=2\">Privacy Policy</a></li>\n <li><a href=\"__SITE__/page.php?pid=7\">Terms & Conditions</a></li>\n <li><a href=\"__SITE__/page.php?pid=3\">FAQ</a></li>\n  <li><a href=\"__SITE__/page.php?pid=8\">Powered by qEngine</a></li>\n</ul>\n',  '0',  0);

DROP TABLE IF EXISTS `__PREFIX__module`;
CREATE TABLE `__PREFIX__module` (
  `mod_id` varchar(255) NOT NULL DEFAULT '',
  `mod_type` enum('general','shipping','payment') NOT NULL DEFAULT 'general',
  `mod_name` varchar(255) NOT NULL DEFAULT '',
  `mod_desc` text NOT NULL,
  `mod_version` varchar(10) NOT NULL DEFAULT '',
  `mod_css` varchar(255) NOT NULL,
  `mod_js` varchar(255) NOT NULL,
  `mod_enabled` char(1) NOT NULL DEFAULT '',
  PRIMARY KEY (`mod_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__module` (`mod_id`, `mod_type`, `mod_name`, `mod_desc`, `mod_version`, `mod_css`, `mod_js`, `mod_enabled`) VALUES
('box', 'general',  'Box',  'A simple module to display static html for your page, without editing .tpl files, best used with qE 4.x\'s Module Manager.', '1.0.0',  '', '', '1'),
('page_gallery',  'general',  'Page Gallery', 'Display selected pages or categories or groups anywhere!', '2.0.0',  '', '', '1'),
('qbanner', 'general',  'qBanner',  'Use this module to upload & display banners.', '1.0.0',  '', '', '1'),
('qcomment',  'general',  'qComment', 'Add user comments & user ratings to your site and your modules, easily!',  '3.0.0',  '', '', '1'),
('qmenu', 'general',  'qMenu',  'Use qMenu module to display your designed menu easily!', '1.0.0',  '', '', '1'),
('qstats',  'general',  'Simple Stats', 'This module replaces qEngine\'s old simple statistics of visitors\' hits & visits.', '1.0.0',  '', '', '1'),
('slideshow', 'general',  'Slideshow',  'This module to replace qEngine\'s old featured contents.', '1.0.0',  'slideshow.css',  '', '1'),
('ztopwatch', 'general',  'Ztopwatch',  'This module replaces the old stopwatch in qEngine 1',  '1.0.0',  '', '', '1');

DROP TABLE IF EXISTS `__PREFIX__module_pos`;
CREATE TABLE `__PREFIX__module_pos` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mod_id` varchar(255) NOT NULL,
  `mod_title` varchar(255) NOT NULL,
  `mod_config` text NOT NULL,
  `mod_pos` char(2) NOT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__module_pos` (`idx`, `mod_id`, `mod_title`, `mod_config`, `mod_pos`) VALUES
(1, 'box',  'Add Anything!',  '&lt;p&gt;You can easily adds any HTML or JavaScript tags by editing this module, or create a new box, by using Box Module in ACP &gt; Modules &gt; Layout.&lt;/p&gt;\r\n\r\n&lt;p&gt;Add Google AdSense, Facebook Feeds, Twitter Updates, by editing this module.&lt;/p&gt;',  'R1'),
(2, 'box',  'Info Box', '&lt;p&gt;Manage this module from ACP. Display up to 40 modules easily!&lt;/p&gt;\r\n\r\n&lt;p&gt;You can also remove this information from Module Management.&lt;/p&gt;\r\n\r\n&lt;p&gt;In default skin, this module appears on the right.&lt;/p&gt;', 'L2'),
(3, 'qbanner',  'Banner', '', 'L1'),
(4, 'qmenu',  'Tools',  'menu=footer_menu', 'B1'),
(5, 'qmenu',  'Pages',  'menu=page_menu', 'B1'),
(9, 'qstats', 'Simple Stats', '', 'R2');

DROP TABLE IF EXISTS `__PREFIX__notification`;
CREATE TABLE `__PREFIX__notification` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `notify_time` int(10) unsigned NOT NULL,
  `notify_from` varchar(255) NOT NULL,
  `notify_to` varchar(255) NOT NULL,
  `notify_admin` enum('0','1') NOT NULL DEFAULT '0',
  `notify_subject` varchar(255) NOT NULL,
  `notify_url` varchar(255) NOT NULL,
  `notify_read` enum('0','1') NOT NULL DEFAULT '0',
  `notify_popup` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`idx`),
  KEY `notify_to` (`notify_to`),
  KEY `notify_admin` (`notify_admin`),
  KEY `notify_popup` (`notify_popup`),
  KEY `notify_from` (`notify_from`),
  KEY `notify_read` (`notify_read`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__page`;
CREATE TABLE `__PREFIX__page` (
  `group_id` varchar(5) NOT NULL,
  `cat_id` int(10) unsigned NOT NULL,
  `page_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `permalink` varchar(255) NOT NULL,
  `page_image` varchar(255) NOT NULL DEFAULT '',
  `page_date` date NOT NULL DEFAULT '0000-00-00',
  `page_time` time NOT NULL,
  `page_unix` int(10) unsigned NOT NULL,
  `page_title` varchar(255) NOT NULL DEFAULT '',
  `page_keyword` varchar(255) NOT NULL,
  `page_body` text NOT NULL,
  `page_author` varchar(255) NOT NULL,
  `page_related` varchar(255) NOT NULL,
  `page_allow_comment` char(1) NOT NULL DEFAULT '0',
  `last_update` int(10) unsigned NOT NULL,
  `page_rating` decimal(3,2) unsigned NOT NULL,
  `page_comment` int(10) unsigned NOT NULL,
  `page_list` char(1) NOT NULL,
  `page_hit` int(10) unsigned NOT NULL,
  `page_img_tmp` varchar(255) NOT NULL DEFAULT '',
  `page_attachment` varchar(255) NOT NULL DEFAULT '',
  `page_attachment_stat` int(10) unsigned NOT NULL,
  `page_download` varchar(15) NOT NULL,
  `page_pinned` char(1) NOT NULL DEFAULT '0',
  `page_status` enum('D','P','M','A','H') NOT NULL DEFAULT 'D',
  `page_template` varchar(255) NOT NULL,
  `page_mode` enum('raw','html') NOT NULL DEFAULT 'html',
  PRIMARY KEY (`page_id`),
  KEY `group_id` (`group_id`),
  KEY `cat_id` (`cat_id`),
  KEY `page_author` (`page_author`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__page` (`group_id`, `cat_id`, `page_id`, `permalink`, `page_image`, `page_date`, `page_time`, `page_unix`, `page_title`, `page_keyword`, `page_body`, `page_author`, `page_related`, `page_allow_comment`, `last_update`, `page_rating`, `page_comment`, `page_list`, `page_hit`, `page_img_tmp`, `page_attachment`, `page_attachment_stat`, `page_download`, `page_pinned`, `page_status`, `page_template`, `page_mode`) VALUES
('GENPG', 1,  1,  'welcome.php',  '', '2011-11-11', '14:15:00', 1321017300, 'Welcome',  'add,your,keyword,here,qengine,c97net', '<p>Welcome to our site, please enjoy your stay here. If you have any question, please contact us.</p>\r\n<p>This is an example of a page, you could edit this to put information about yourself or your site so readers know where you are coming from. As mentioned before, you can create as many pages like this one.</p>\r\n<p>You can edit this text in Admin &gt; Page Manager.</p>',  'admin',  '', '0',  1447165085, 0.00, 0,  '0',  111,  '', '', 0,  '', '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  2,  'privacy-policy.php', '', '2011-11-11', '14:30:00', 1321018200, 'Privacy Policy', '', '<h2>Information that is gathered from visitors</h2>\r\n<p>In common with other websites, log files are stored on the web server saving details such as the visitor\'s IP address, browser type, referring page and time of visit.</p>\r\n<p>Cookies may be used to remember visitor preferences when interacting with the website.</p>\r\n<p>Where registration is required, the visitor\'s email and a username will be stored on the server.</p>\r\n<h2>How the Information is used</h2>\r\n<p>The information is used to enhance the vistor\'s experience when using the website to display personalised content and possibly advertising.</p>\r\n<p>E-mail addresses will not be sold, rented or leased to 3rd parties.</p>\r\n<p>E-mail may be sent to inform you of news of our services or offers by us or our affiliates.</p>\r\n<h2>Visitor Options</h2>\r\n<p>If you have subscribed to one of our services, you may unsubscribe by following the instructions which are included in e-mail that you receive.</p>\r\n<p>You may be able to block cookies via your browser settings but this may prevent you from access to certain features of the website.</p>\r\n<h2>Cookies</h2>\r\n<p>Cookies are small digital signature files that are stored by your web browser that allow your preferences to be recorded when visiting the website. Also they may be used to track your return visits to the website.</p>\r\n<p>3rd party advertising companies may also use cookies for tracking purposes.</p>\r\n<h2>Google Ads</h2>\r\n<p>Google, as a third party vendor, uses cookies to serve ads.</p>\r\n<p>Google\'s use of the DART cookie enables it to serve ads to visitors based on their visit to sites they visit on the Internet.</p>\r\n<p>Website visitors may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy.</p>\r\n<p>(last updated March 2009)<br />Based on <a href=\"http://www.freeprivacypolicy.org/\">FPP</a></p>', 'admin',  '', '1',  1509379812, 0.00, 0,  '1',  71, '', '', 6,  ',5,',  '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  3,  'faqs.php', '', '2011-11-11', '00:00:00', 1320944400, 'FAQ&#039;s', '', '<p>Here you will find answers to many of your questions. If there is something which you cannot find the answer to, let us know and we will add your question to this list.</p>',  'admin',  '', '1',  1366442718, 0.00, 0,  '1',  69, '', '', 0,  '', '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  4,  'about-us.php', '', '2011-11-11', '00:00:00', 1320966000, 'About Us', '', '<p>Tell who you are, what you do, and anything else. Company history and the chairman will be a nice addition.</p>', 'admin',  '', '1',  1443117458, 0.00, 0,  '1',  338,  '', '', 3,  '', '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  6,  'contact-us.php', '', '2011-11-11', '00:00:00', 1320944400, 'Contact Us', '', '<p>Put your contact information here, such as office hour, parking spot, direction, etc.</p>\r\n<p>Change this text in Admin &gt; Page Manager</p>', 'admin',  '', '0',  1366442727, 0.00, 0,  '0',  0,  '', '', 0,  '', '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  7,  'terms-and-conditions.php', '', '2011-11-11', '00:00:00', 1320944400, 'Terms &amp; Conditions', '', '<p>Welcome to our website. If you continue to browse and use this website, you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern [business name]\'s relationship with you in relation to this website. If you disagree with any part of these terms and conditions, please do not use our website.</p>\r\n<p>The term \'[business name]\' or \'us\' or \'we\' refers to the owner of the website whose registered office is [address]. Our company registration number is [company registration number and place of registration]. The term \'you\' refers to the user or viewer of our website.</p>\r\n<p>The use of this website is subject to the following terms of use:</p>\r\n<ul>\r\n<li>The content of the pages of this website is for your general information and use only. It is subject to change without notice.</li>\r\n<li>This website uses cookies to monitor browsing preferences. If you do allow cookies to be used, the following personal information may be stored by us for use by third parties: [insert list of information].</li>\r\n<li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>\r\n<li>Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements.</li>\r\n<li>This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.</li>\r\n<li>All trade marks reproduced in this website which are not the property of, or licensed to, the operator are acknowledged on the website.</li>\r\n<li>Unauthorised use of this website may give rise to a claim for damages and/or be a criminal offence.</li>\r\n<li>From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).</li>\r\n<li>Your use of this website and any dispute arising out of such use of the website is subject to the laws of England, Northern Ireland,&nbsp;Scotland and Wales.</li>\r\n</ul>',  'admin',  '', '1',  1366442731, 0.00, 0,  '1',  30, '', '', 0,  '', '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  8,  'powered-by-qengine.php', '', '2011-11-11', '00:00:00', 1320944400, 'Powered by qEngine', '', '<p>This site is using qEngine CMS, a simple CMS engine created by <a href=\"http://www.c97.net\">C97.net</a>. qEngine is very easy to use &amp; maintain, no need to understand PHP, and it\'s <strong>FREE!</strong> If you are interested to use this awesome script please visit <a href=\"http://www.c97.net\">www.c97.net</a> now!</p>',  'admin',  '', '1',  1366442735, 0.00, 0,  '1',  24, '', '', 0,  '', '0',  'P',  'page_default.tpl', 'html'),
('NEWS',  2,  9,  'news/site-is-now-up-and-ready.php',  '', '2011-11-11', '00:00:00', 1320966000, 'Site is Now Up &amp; Ready', '', '<h2>Congratulations!</h2>\r\n<p>You have succesfully installed qEngine!<br />To learn more about qEngine, please visit <a href=\"http://www.c97.net\" target=\"_blank\">www.c97.net</a>.<br /><br />(To remove this message, go to ACP &gt; Contents &gt; Manage Contents)</p>', 'admin',  '', '0',  1469804396, 0.00, 0,  '1',  83, '', '', 0,  '', '0',  'P',  'page_default.tpl', 'html'),
('QBANR', 0,  10, '', 'banner2.jpg',  '0000-00-00', '00:00:00', 0,  'The Banner', '#',  'This page is part of qBanner module. Please use qBanner Manager to edit this page.', '', '', '', 0,  0.00, 0,  '', 0,  '', '', 0,  '', '0',  'P',  '', 'html'),
('SSHOW', 0,  11, '', 'slide1.jpg', '0000-00-00', '00:00:00', 0,  'Change this content from ACP', '#',  'This page is part of SlideShow module. Please use SlideShow Manager to edit this page.', '', '', '', 0,  0.00, 0,  '', 0,  '', '', 0,  '', '0',  'P',  '', 'html'),
('SSHOW', 0,  12, '', 'slide2.jpg', '0000-00-00', '00:00:00', 0,  'The Mountain', '#',  'This page is part of SlideShow module. Please use SlideShow Manager to edit this page.', '', '', '', 0,  0.00, 0,  '', 0,  '', '', 0,  '', '0',  'P',  '', 'html'),
('SSHOW', 0,  13, '', 'slide3.jpg', '0000-00-00', '00:00:00', 0,  'The city', '#',  'This page is part of SlideShow module. Please use SlideShow Manager to edit this page.', '', '', '', 0,  0.00, 0,  '', 0,  '', '', 0,  '', '0',  'P',  '', 'html');

DROP TABLE IF EXISTS `__PREFIX__page_cat`;
CREATE TABLE `__PREFIX__page_cat` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `group_id` varchar(5) NOT NULL,
  `parent_id` int(10) unsigned NOT NULL,
  `permalink` varchar(255) NOT NULL,
  `cat_name` varchar(255) NOT NULL,
  `cat_details` text NOT NULL,
  `cat_image` varchar(255) NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `group_id` (`group_id`),
  KEY `parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__page_cat` (`idx`, `group_id`, `parent_id`, `permalink`, `cat_name`, `cat_details`, `cat_image`) VALUES
(1, 'GENPG',  0,  'general-pages.php',  'General Pages',  '<p>General Pages</p>', ''),
(2, 'NEWS', 0,  'news.php', 'General News', '<p>General News</p>',  '');

DROP TABLE IF EXISTS `__PREFIX__page_group`;
CREATE TABLE `__PREFIX__page_group` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `group_id` varchar(5) NOT NULL,
  `group_title` varchar(255) NOT NULL,
  `group_notes` varchar(255) NOT NULL,
  `all_cat_list` char(1) NOT NULL,
  `cat_list` char(1) NOT NULL,
  `page_cat` char(1) NOT NULL,
  `page_image` char(1) NOT NULL,
  `page_image_size` int(10) unsigned NOT NULL,
  `page_thumb` int(10) unsigned NOT NULL,
  `page_gallery` char(1) NOT NULL,
  `page_gallery_thumb` int(10) unsigned NOT NULL,
  `page_author` char(1) NOT NULL,
  `page_comment` varchar(15) NOT NULL,
  `page_attachment` char(1) NOT NULL,
  `page_download` varchar(15) NOT NULL,
  `page_date` char(1) NOT NULL,
  `page_folder` varchar(25) NOT NULL,
  `page_sort` enum('t','d') NOT NULL DEFAULT 't',
  `hidden_private` char(1) NOT NULL,
  `group_template` varchar(255) NOT NULL,
  `page_template` varchar(255) NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `group_id` (`group_id`),
  KEY `hidden_private` (`hidden_private`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__page_group` (`idx`, `group_id`, `group_title`, `group_notes`, `all_cat_list`, `cat_list`, `page_cat`, `page_image`, `page_image_size`, `page_thumb`, `page_gallery`, `page_gallery_thumb`, `page_author`, `page_comment`, `page_attachment`, `page_download`, `page_date`, `page_folder`, `page_sort`, `hidden_private`, `group_template`, `page_template`) VALUES
(1, 'GENPG',  'Common Page',  'General pages, eg: company history, about you, etc. (please do NOT remove this content type, you can edit this message in ACP &gt; Contents &gt; Manage Types)', '1',  '1',  '1',  '1',  500,  200,  '1',  200,  '1',  'pagecomment',  '1',  ',3,4,',  '0',  '', 't',  '0',  'body_default.tpl', 'page_default.tpl'),
(2, 'NEWS', 'News', 'Site news (please do NOT remove this content type, you can edit this message in ACP &gt; Contents &gt; Manage Types)', '1',  '1',  '1',  '1',  500,  200,  '0',  0,  '0',  '0',  '0',  '', '1',  'news', 't',  '0',  'body_news.tpl',  'page_default.tpl'),
(3, 'QBANR',  'qBanner',  'qBanner module storage', '0',  '0',  '0',  '1',  0,  0,  '0',  0,  '0',  '0',  '', '', '0',  '', 't',  '1',  'body_default.tpl', 'page_default.tpl'),
(4, 'SSHOW',  'Slideshow',  'Slideshow module storage', '0',  '0',  '0',  '1',  0,  0,  '0',  0,  '0',  '0',  '', '', '0',  '', 't',  '1',  'body_default.tpl', 'page_default.tpl');


DROP TABLE IF EXISTS `__PREFIX__permalink`;
CREATE TABLE `__PREFIX__permalink` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `url` varchar(255) NOT NULL,
  `target_script` varchar(255) NOT NULL,
  `target_idx` varchar(255) NOT NULL,
  `target_param` varchar(255) NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `url` (`url`),
  KEY `target_script` (`target_script`),
  KEY `target_idx` (`target_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__permalink` (`idx`, `url`, `target_script`, `target_idx`, `target_param`) VALUES
(1, 'welcome.php',  'page.php', '1',  ''),
(2, 'privacy-policy.php', 'page.php', '2',  ''),
(3, 'faqs.php', 'page.php', '3',  ''),
(4, 'about-us.php', 'page.php', '4',  ''),
(5, 'contact-us.php', 'page.php', '6',  ''),
(6, 'terms-and-conditions.php', 'page.php', '7',  ''),
(7, 'powered-by-qengine.php', 'page.php', '8',  ''),
(8, 'news/site-is-now-up-and-ready.php',  'page.php', '9',  ''),
(9, 'general-pages.php',  'page.php', '1',  'list'),
(10,  'news.php', 'page.php', '2',  'list');

DROP TABLE IF EXISTS `__PREFIX__qadmin_log`;
CREATE TABLE `__PREFIX__qadmin_log` (
  `log_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `log_date` int(10) unsigned NOT NULL,
  `log_file` varchar(255) NOT NULL,
  `log_table` varchar(255) NOT NULL,
  `log_user` varchar(255) NOT NULL,
  `log_ip` varchar(45) NOT NULL,
  `log_pid` varchar(255) NOT NULL,
  `log_title` varchar(255) NOT NULL,
  `log_action` int(10) unsigned NOT NULL,
  `log_previous` text NOT NULL,
  `log_now` text NOT NULL,
  PRIMARY KEY (`log_id`),
  KEY `log_ip` (`log_ip`),
  KEY `log_user` (`log_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__qcomment`;
CREATE TABLE `__PREFIX__qcomment` (
  `comment_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mod_id` varchar(255) NOT NULL DEFAULT '',
  `item_id` varchar(80) NOT NULL,
  `item_title` varchar(255) NOT NULL,
  `item_url` varchar(255) NOT NULL,
  `comment_user` varchar(255) NOT NULL DEFAULT '',
  `comment_title` varchar(255) NOT NULL DEFAULT '',
  `comment_body` text NOT NULL,
  `comment_date` date NOT NULL DEFAULT '0000-00-00',
  `comment_rate` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `comment_helpful` varchar(16) NOT NULL,
  `comment_approve` char(1) NOT NULL DEFAULT '',
  PRIMARY KEY (`comment_id`),
  KEY `mod_id` (`mod_id`),
  KEY `item_id` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='No comment!';


DROP TABLE IF EXISTS `__PREFIX__qcomment_set`;
CREATE TABLE `__PREFIX__qcomment_set` (
  `group_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `comment_mode` char(1) NOT NULL,
  `comment_approval` char(1) NOT NULL,
  `member_only` char(1) NOT NULL,
  `unique_comment` char(1) NOT NULL,
  `comment_helpful` char(1) NOT NULL,
  `comment_on_comment` char(1) NOT NULL,
  `captcha` char(1) NOT NULL,
  `detail` char(1) NOT NULL,
  `mod_id` varchar(15) NOT NULL,
  `notes` varchar(255) NOT NULL,
  PRIMARY KEY (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__qcomment_set` (`group_id`, `comment_mode`, `comment_approval`, `member_only`, `unique_comment`, `comment_helpful`, `comment_on_comment`, `captcha`, `detail`, `mod_id`, `notes`) VALUES
(1, '2',  '0',  '0',  '0',  '0',  '1',  '0',  '0',  'conc', 'Comments on comments'),
(3, '2',  '1',  '0',  '0',  '0',  '1',  '0',  '1',  'pagecomment',  'Page Comment');

DROP TABLE IF EXISTS `__PREFIX__stats_daily`;
CREATE TABLE `__PREFIX__stats_daily` (
  `stats_date` date NOT NULL,
  `stats_hit` int(10) unsigned NOT NULL,
  `stats_visit` int(10) unsigned NOT NULL,
  PRIMARY KEY (`stats_date`),
  KEY `stats_hit` (`stats_hit`),
  KEY `stats_visit` (`stats_visit`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__stats_ip`;
CREATE TABLE `__PREFIX__stats_ip` (
  `ip_address` varchar(45) NOT NULL,
  `last_update` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ip_address`),
  KEY `last_update` (`last_update`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__user`;
CREATE TABLE `__PREFIX__user` (
  `user_id` varchar(80) NOT NULL DEFAULT '',
  `user_passwd` varchar(255) NOT NULL DEFAULT '',
  `user_email` varchar(255) NOT NULL DEFAULT '',
  `user_level` char(1) NOT NULL DEFAULT '1',
  `user_since` date NOT NULL DEFAULT '0000-00-00',
  `admin_level` char(1) NOT NULL DEFAULT '0',
  `reset_passwd` varchar(16) NOT NULL DEFAULT '',
  `user_activation` varchar(16) NOT NULL DEFAULT '',
  `axsrf_token` varchar(32) NOT NULL,
  `user_notes` text NOT NULL,
  PRIMARY KEY (`user_id`),
  KEY `user_passwd` (`user_passwd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Member profile & billing address';