INSERT INTO `__PREFIX__config` (`idx`, `group_id`, `config_id`, `config_value`) VALUES
(81,  'cart', 'featured_product', ''),
(84,  'cart', 'delete_old_orders',  '30'),
(85,  'cart', 'buy_display_cart', '1'),
(86,  'cart', 'order_id_format',  '1'),
(87,  'cart', 'order_id_prefix',  'CE'),
(88,  'cart', 'manage_stock', '1'),
(94,  'cart', 'ship_area',  'world'),
(95,  'cart', 'tax_base', 'billing'),
(96,  'cart', 'hide_ship',  '1'),
(113, 'cart', 'xc_version', '7.0.0/20180212'),
(114, 'cart', 'allow_xpress', '1'),
(115, 'mod_pay_paypal', 'sandbox',  '0'),
(116, 'mod_pay_paypal', 'currency_code',  'USD'),
(117, 'mod_pay_paypal', 'bussiness',  'seller@c97.net'),
(118, 'mod_pay_paypal', 'ipn',  '1'),
(119, 'mod_pay_cheque', 'recipient',  'My Name'),
(120, 'mod_pay_bank', 'bankname', 'My Bank'),
(121, 'mod_pay_bank', 'bankaddress',  ''),
(122, 'mod_pay_bank', 'bankcode', 'Bank code (BIC/IBAN/SWIFT)'),
(123, 'mod_pay_bank', 'account',  '1234567890'),
(124, 'mod_pay_bank', 'holder', 'My Name'),
(125, 'mod_ship_percent', 'fee',  '10'),
(126, 'mod_ship_item',  'per_item', '10'),
(127, 'mod_ship_cod', 'fee',  '5'),
(128, 'mod_ship_pickup',  'fee',  '10'),
(129, 'mod_ship_free',  'minimum',  '1000000'),
(132, 'mod_pay_paypal', 'conversion_rate',  ''),
(158, 'var',  'tax',  'Tax Exempt'),
(159, 'var',  'tax',  'VAT'),
(160, 'var',  'tax',  'Grocery'),
(161, 'var',  'tax_160',  'a:4:{s:4:\"city\";s:1:\"5\";s:5:\"state\";s:1:\"5\";s:6:\"nation\";s:1:\"5\";s:5:\"world\";s:1:\"0\";}'),
(162, 'var',  'tax_158',  'a:4:{s:4:\"city\";s:1:\"0\";s:5:\"state\";s:1:\"0\";s:6:\"nation\";s:1:\"0\";s:5:\"world\";s:1:\"0\";}'),
(163, 'var',  'tax_159',  'a:4:{s:4:\"city\";s:2:\"10\";s:5:\"state\";s:2:\"10\";s:6:\"nation\";s:2:\"10\";s:5:\"world\";s:1:\"0\";}'),
(164, 'cart', 'display_price_tax',  'separate'),
(165, 'mod_ship_weight',  'fee',  'a:4:{s:4:\"city\";s:2:\"10\";s:5:\"state\";s:2:\"20\";s:7:\"country\";s:2:\"30\";s:5:\"world\";s:2:\"40\";}');


DROP TABLE IF EXISTS `__PREFIX__gift`;
CREATE TABLE `__PREFIX__gift` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `gift_code` varchar(32) NOT NULL,
  `master_code` varchar(25) NOT NULL,
  `gift_value` decimal(10,2) NOT NULL DEFAULT '0.00',
  `gift_pct` enum('0','1') NOT NULL DEFAULT '0',
  `min_purchase` decimal(10,2) NOT NULL DEFAULT '0.00',
  `valid_date` date NOT NULL DEFAULT '0000-00-00',
  `coupon_type` enum('once','multi') NOT NULL DEFAULT 'once',
  `redeem_email` varchar(255) NOT NULL,
  `redeem_msg` text NOT NULL,
  `redeem_sent` enum('0','1') NOT NULL DEFAULT '0',
  `redeem_order_id` varchar(16) NOT NULL,
  `redeem_user_id` varchar(80) NOT NULL,
  `redeem_date` int(10) unsigned NOT NULL,
  `redeem_purchase` decimal(10,2) NOT NULL,
  PRIMARY KEY (`idx`),
  UNIQUE KEY `gift_code` (`gift_code`),
  KEY `master_code` (`master_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `__PREFIX__language` (`lang_id`, `lang_key`, `lang_value`) VALUES
('en',  'l_address',  'Address'),
('en',  'l_add_buy',  '<span class=\"glyphicon glyphicon-shopping-cart\"></span>'),
('en',  'l_add_wish', 'Add to Wishlist'),
('en',  'l_add_wishlist', 'Add to Wishlist'),
('en',  'l_ask_us_title', 'Ask Us About This Product'),
('en',  'l_best_seller',  'Best Sellers'),
('en',  'l_bill_address', 'Billing Address'),
('en',  'l_bill_detail',  'Billing Details'),
('en',  'l_buy_together', 'Buy Together'),
('en',  'l_cant_buy', 'Not Available'),
('en',  'l_cart_call_price',  'Please call us to buy this product!'),
('en',  'l_cart_empty', 'Your shopping cart is empty'),
('en',  'l_category', 'Category'),
('en',  'l_change_address', 'Change Address'),
('en',  'l_checkout', 'Checkout'),
('en',  'l_city', 'City'),
('en',  'l_city_empty', 'Invalid City'),
('en',  'l_confirm_address',  'Confirm Address'),
('en',  'l_contact_product',  'Contact Us About This Product'),
('en',  'l_copy_bill',  'Copy my billing address'),
('en',  'l_country',  'Country'),
('en',  'l_country_empty',  'Invalid Country'),
('en',  'l_coupon_disc',  'Coupon Discount'),
('en',  'l_coupon_info',  'Coupon value: %1$s<br />Minimum purchase: %2$s<br />Valid until: %3$s'),
('en',  'l_courier_free', 'Free'),
('en',  'l_customize_product',  'Customize Your Product'),
('en',  'l_date_asc', 'Date Ascending'),
('en',  'l_date_dsc', 'Date Descending'),
('en',  'l_default_address',  '<b>(Default Shipping Address)</b>'),
('en',  'l_description',  'Description'),
('en',  'l_detail', 'Detail'),
('en',  'l_detail_call_price',  '<b><i><a href=\"#\" onclick=\"open_contact()\">Call For Price</a></i></b>'),
('en',  'l_digital_icon', '<span class=\"glyphicon glyphicon-download-alt text-success\"></span>'),
('en',  'l_digital_icon_small', '<span class=\"glyphicon glyphicon-download-alt text-success\"></span>'),
('en',  'l_digital_not_login',  'This is a digital product. Please login before purchasing!'),
('en',  'l_discount', '%s%% off'),
('en',  'l_district', 'District'),
('en',  'l_district_empty', 'Invalid District'),
('en',  'l_distro', 'Brands'),
('en',  'l_distro_info',  'Distributor/Manufacturer Information'),
('en',  'l_distro_product', 'Products By %1$s'),
('en',  'l_empty_wishlist', 'Empty Wish List'),
('en',  'l_express_checkout', 'Express Checkout'),
('en',  'l_express_checkout_tips',  'Please fill this form for Express Checkout. You can not access My Account to see order history, wish list, subsription, and other member only feature using Express Checkout.'),
('en',  'l_express_checkout_why', 'If you don\'t want to create an account with us, click here for <a href=\"profile.php?mode=xpress\">Express Checkout</a>.'),
('en',  'l_fee',  'Fee'),
('en',  'l_free', 'free'),
('en',  'l_gift_coupon_input',  'If you have a gift coupon, please enter the code here:'),
('en',  'l_gift_coupon_warning',  'Currently, you have an <a href=\"coupon.php?view=%1$s\">active coupon</a>, if you enter a new one, the previous one will be replaced.'),
('en',  'l_grid', 'Grid'),
('en',  'l_how_to_pay', 'How To Pay'),
('en',  'l_if_applicable',  'If Applicable'),
('en',  'l_include_out_of_stock', 'Include out-of-stock items'),
('en',  'l_invalid_distro_id',  'Invalid Distributor/Manufacturer Information'),
('en',  'l_invoice',  'Invoice'),
('en',  'l_issue_date', 'Issue Date'),
('en',  'l_item_in_cart', 'This item is already in your shopping cart.'),
('en',  'l_last_item',  'Last Items'),
('en',  'l_list', 'List'),
('en',  'l_list_call_price',  '<span style=\"font-size:small\">Call For Price</span>'),
('en',  'l_list_style', 'List Style'),
('en',  'l_mail_coupon',  '%s - Your free gift coupon / voucher'),
('en',  'l_mail_order_admin_subject', '%1$s - New Order - ID: %2$s'),
('en',  'l_mail_order_cancel',  '%1$s - Your order has been cancelled - #%2$s'),
('en',  'l_mail_order_cancel_request',  '%1$s - Order Cancellation Requested - #%2$s'),
('en',  'l_mail_order_digital_subject', '%1$s - Your digital order has been shipped - #%2$s'),
('en',  'l_mail_order_pending', '%1$s - Your order has been pended - #%2$s'),
('en',  'l_mail_order_process', '%1$s - Your order is now on process - #%2$s'),
('en',  'l_mail_order_ship',  '%1$s - Your order has been shipped - #%2$s'),
('en',  'l_mail_order_subject', '%1$s - Your Order  - #%2$s'),
('en',  'l_manufacturer', 'Manufacturer'),
('en',  'l_max_buy',  'Maximum Purchase'),
('en',  'l_method', 'Method'),
('en',  'l_min_buy',  'Minimum Purchase'),
('en',  'l_min_max_buy_err',  'Minimum/maximum buying quantity is not complied.'),
('en',  'l_mycart_text',  '%1$s items for %2$s'),
('en',  'l_my_address', 'My Addresses'),
('en',  'l_my_address_why', 'Manage your billing &amp; shipping addresses.'),
('en',  'l_my_cart',  'My Cart'),
('en',  'l_my_files', 'My Files'),
('en',  'l_my_files_none',  'Sorry, we can\'t find any purchased files.'),
('en',  'l_my_files_why', 'Manage your files, images, etc.'),
('en',  'l_my_order', 'My Orders'),
('en',  'l_my_order_title', 'Order Details for Order ID %1$s on %2$s'),
('en',  'l_my_wishlist',  'My Wishlist'),
('en',  'l_my_wishlist_why',  'Your wishlist contains a list of products which you may want to purchase in the future.'),
('en',  'l_new_item', 'New Items'),
('en',  'l_next', 'Next'),
('en',  'l_notify_available', 'Notify Me When Product is Available'),
('en',  'l_notify_us',  'Report This Listing'),
('en',  'l_no_item_cart', 'There is no item in your shopping cart.'),
('en',  'l_ones_wishlist',  '%1$s\'s Wishlist'),
('en',  'l_order_date', 'Order Date'),
('en',  'l_order_note', 'Order Notes'),
('en',  'l_order_note_why', 'Enter some order notes here (optional).'),
('en',  'l_order_status', 'Order Status'),
('en',  'l_payment_fee',  'Payment Fee'),
('en',  'l_pay_method', 'Payment Method'),
('en',  'l_pay_method_why', 'How would you like to pay?'),
('en',  'l_pay_redir',  'You will be redirected to the payment portal'),
('en',  'l_pay_redir_3s', 'Click here, if you are not redirected in 3 seconds!'),
('en',  'l_pay_status', 'Payment Status'),
('en',  'l_phone_number', 'Telephone Number'),
('en',  'l_place_order',  'Place Order'),
('en',  'l_price',  'Price'),
('en',  'l_price_asc',  'Price Ascending'),
('en',  'l_price_dsc',  'Price Descending'),
('en',  'l_price_range',  'Price Range'),
('en',  'l_print_invoice',  'Print Invoice'),
('en',  'l_product_added',  'Product has already been added to your shopping cart!'),
('en',  'l_product_search', 'For product search, click here'),
('en',  'l_promo',  'Promo'),
('en',  'l_purchase', 'Purchase'),
('en',  'l_purchase_summary', 'Purchase Summary'),
('en',  'l_quantity', 'Quantity'),
('en',  'l_remove_wishlist',  'Remove Wishlist'),
('en',  'l_review', 'Reviews'),
('en',  'l_see_also', 'See Also'),
('en',  'l_select_city',  'Select a City'),
('en',  'l_select_country', 'Select a Country'),
('en',  'l_select_district',  'Select a District'),
('en',  'l_select_state', 'Select a State'),
('en',  'l_share_title',  'Share This Product'),
('en',  'l_share_wishlist', 'Share this wish list by sharing this link'),
('en',  'l_ship_address', 'Shipping Address'),
('en',  'l_ship_date',  'Ship Date'),
('en',  'l_ship_detail',  'Shipping Details'),
('en',  'l_ship_fee', 'Shipping Fee'),
('en',  'l_ship_fee_for', 'Shipping fee for %1$s %2$s'),
('en',  'l_ship_method',  'Shipping Method'),
('en',  'l_ship_method_why',  'Please choose how your would like your goods to be shipped.'),
('en',  'l_ship_weight',  'Shipping Weight'),
('en',  'l_shop_disc',  'Shop Discount'),
('en',  'l_sku',  'SKU'),
('en',  'l_sort_by',  'Sort By'),
('en',  'l_specification',  'Specification'),
('en',  'l_state',  'County/State/Province'),
('en',  'l_state_empty',  'Invalid State'),
('en',  'l_stock_empty',  'Out of stock'),
('en',  'l_stock_ready',  '%s available'),
('en',  'l_stock_status', 'Stock Status'),
('en',  'l_subtotal', 'Subtotal'),
('en',  'l_tax',  'Tax'),
('en',  'l_tax_based_wo_ship',  'Tax Base w/o Shipping'),
('en',  'l_tell_us_subject',  'About a listing of %s'),
('en',  'l_title_asc',  'Title Ascending'),
('en',  'l_title_dsc',  'Title Descending'),
('en',  'l_toolbox',  'Toolbox'),
('en',  'l_total',  'Total'),
('en',  'l_trx_history',  'Transaction History'),
('en',  'l_trx_history_why',  'See current &amp; previous transactions.'),
('en',  'l_trx_print_footer', '<p>This electronic invoice was generated by our Order Processing System. No signature is required. A copy ofthis invoice will not accompany your package. Please retain this email.</p><p>The Shipping Charge includes any shipping and handling fees.</p><div style=\"border: solid 1px #999; padding:10px; text-align:center\"><p><b>Thank you for shopping at <a href=\"%1$s\">%2$s</a></b></p></div>'),
('en',  'l_update_cart',  'Update Cart'),
('en',  'l_update_cart_why',  'If you changed the quantity, please update cart'),
('en',  'l_view_file',  '<a href=\"viewfile.php?f=%s\" class=\"lightbox\">View File</a>'),
('en',  'l_with_tax', 'w/ Tax %s'),
('en',  'l_with_tax_guest', '-'),
('en',  'l_xe_help',  'Display Prices in Other Currency'),
('en',  'l_xpress_tag', '<br />[ <i>Express Checkout</i> ]'),
('en',  'l_zipcode',  'Zip/Postcode'),
('en',  'mail.ask_product', '<p>A visitor at your website is asking for more information regarding {$title} - <a href=\"{$site_url}/{$url}\">{$site_url}/{$url}</a></p><p style=\"border:solid 1px #999;width:290px; text-align:center; padding:5px\"><b>{$title}</b><br /><a href=\"{$site_url}/{$url}\">{$image}</a><br />{$price}</p><p>Name: {$name}<br />\r\nEmail: {$email}</p><p>The message:<br />\r\n{$tell_body}</p>'),
('en',  'mail.cancel',  '<p><b>Dear {$fullname},</b></p><p>This email is to inform you that on {$today}, we have <b>cancelled</b> your order as below:</p><p>Order Information<br><hr>\r\nOrder ID: {$order_id}<br>\r\nOrder date: {$order_date}<br>\r\nTo see your order detail, please go to <a href=\"{$site_url}/trx.php?order_id={$order_id}\">{$site_url}/trx.php?order_id={$order_id}</a></p><p>Shipping Address<br /><hr />\r\n{$ship_address}</p>'),
('en',  'mail.checkout',  '<div style=\"padding:10px; border:1px solid #888888; border-top:3px solid darkgreen; width:580px; margin:auto; background:#fff\">\r\n    <h3 align=\"right\">Order Confirmation</h3>\r\n    <p>Dear {$fullname},</p>\r\n    <p>Thank you for ordering at {$shop_name}, here are the details of your order.</p>\r\n    <table border=\"0\" cellpadding=\"3\" cellspacing=\"3\" width=\"100%\">\r\n      <tr>\r\n        <th width=\"40%\">Username</th>\r\n        <td width=\"60%\">{$current_user_id}</td>\r\n      </tr>\r\n      <tr>\r\n        <th width=\"40%\">Order ID</th>\r\n        <td width=\"60%\">{$order_id}</td>\r\n      </tr>\r\n      <tr>\r\n        <th width=\"40%\">Order Date</th>\r\n        <td width=\"60%\">{$today}</td>\r\n      </tr>\r\n      <tr>\r\n        <th width=\"40%\">Payment Method</th>\r\n        <td width=\"60%\">{$payment_method}</td>\r\n      </tr>\r\n      <tr>\r\n        <th width=\"40%\">Shipping Method</th>\r\n        <td width=\"60%\">{$shipping_method}</td>\r\n      </tr>\r\n      <tr>\r\n        <th valign=\"top\" width=\"40%\">Billing Address</th>\r\n        <td width=\"60%\">{$billing_address}</td>\r\n      </tr>\r\n      <tr>\r\n        <th valign=\"top\" width=\"40%\">Shipping Address</th>\r\n        <td width=\"60%\">{$shipping_address}</td>\r\n      </tr>\r\n    </table>\r\n    <table border=\"1\" cellpadding=\"3\" style=\"border-collapse: collapse; border-color:#999;border:solid 1px #999\" width=\"100%\">\r\n      <tr>\r\n        <th class=\"items\" width=\"50%\">Description</th>\r\n        <th class=\"items\" width=\"10%\">Qty</th>\r\n        <th class=\"items\" width=\"20%\">Unit Price</th>\r\n        <th class=\"items\" width=\"20%\">Subtotal</th>\r\n      </tr><!-- BEGINBLOCK checkout_item -->\r\n      <tr>\r\n        <td width=\"48%\">{$title}</td>\r\n        <td align=\"center\" width=\"10%\">{$qty}</td>\r\n        <td align=\"right\" width=\"19%\">{$price}</td>\r\n        <td align=\"right\" width=\"29%\">{$subtotal}</td>\r\n      </tr><!-- ENDBLOCK -->\r\n    </table>\r\n    <table border=\"0\" cellpadding=\"3\" cellspacing=\"3\" width=\"100%\">\r\n      <tr>\r\n        <th width=\"40%\">Sub Total</th>\r\n        <td width=\"60%\">{$total}</td>\r\n      </tr>\r\n      <tr>\r\n        <th width=\"40%\">Coupon Discount</th>\r\n        <td width=\"60%\">{$coupon_disc} {$gift_code}</td>\r\n      </tr>\r\n      <tr>\r\n        <th width=\"40%\">Shipping Fee</th>\r\n        <td width=\"60%\">{$shipping_cost}</td>\r\n      </tr>\r\n      <tr>\r\n        <th width=\"40%\">Payment Fee</th>\r\n        <td width=\"60%\">{$payment_cost}</td>\r\n      </tr>\r\n      <tr>\r\n        <th width=\"40%\">Tax</th>\r\n        <td width=\"60%\">{$tax}</td>\r\n      </tr>\r\n      <tr>\r\n        <th width=\"40%\">Total</th>\r\n        <td width=\"60%\">{$grand_total}</td>\r\n      </tr>\r\n    </table><!-- BEGINIF $howtopay -->\r\n    <div class=\"section\">\r\n      <p>How to Pay Information</p>\r\n    </div>\r\n    <p>You have selected {$payment_method} for payment method. Please read the following information on how to pay for your orders.</p>{$howtopay}<!-- ENDIF -->\r\n    <div class=\"section\">\r\n      <p>Thank you for shopping at <a href=\"{$site_url}\">{$shop_name}</a></p>\r\n    </div>\r\n    <p>This order confirmation has been automatically generated by our order tracking system.</p>\r\n    <p>Should you have any questions about your order, please visit the following url for updated order information: <a href=\"{$trx_check_url}\">{$trx_check_url}</a></p>\r\n    <p>Yours sincerely,<br>\r\n    Customer Service Department<br>\r\n    <b>{$shop_name}</b><br>\r\n    {$shop_address}</p>\r\n  </div>'),
('en',  'mail.checkout_admin',  '<p>You have just got a new order!</p>\r\n<h3>Order Information</h3>\r\n<p><b>Order ID:</b> {$order_id}<br /><b>Order date:</b> {$today}</p><h3>Products</h3><ul><!-- BEGINBLOCK checkout_item_adm --><li>{$where_am_i}: {$qty} x {$title} = {$subtotal}</li><!-- ENDBLOCK --></ul><p><b>Subtotal:</b> {$total}<br /><b>Coupon discount:</b> {$coupon_disc} {$gift_code}<br /><b>Tax:</b> {$tax}<br /><b>Shipping fee:</b> {$shipping_cost}<br /><b>Payment fee:</b> {$payment_cost}<br /><b>Total:</b> {$grand_total}</b></p><h3>Shipping Address</h3><p><b>{$fullname}</b><br />\r\n{$shipping_address}</p><h3>Payment Information</h3><p><b>Selected method of payment:</b> {$payment_method}<br /><b>Payment status:</b> {$payment_status}</p><p>If this order paid using PayPal IPN, be sure to recheck the PayPal log manually from your ACP.</p><p>You can manage this transaction at: <a href=\"{$adm_check_url}\">{$adm_check_url}</a></p>'),
('en',  'mail.coupon',  '<b>Hello there!</b><br>\r\nThis email contains an exclusive gift coupon for use at our website!<br><blockquote><b>Coupon code:</b> {{{$gift_code}}}<br><b>Gift value:</b> {{{$gift_value}}}<br><b>Minimum purchase:</b> {{{$min_purchase}}}<br><b>Valid until:</b> {{{$valid_date}}}<br></blockquote><p>To redeem your coupon:</p><ol><li>Locate the products and add them to your cart.</li><li>Whilst placing your order, enter the coupon code when prompted.</li><li>Your coupon will automatically deduct any savings from your order total.</li></ol><p>Thank you.</p>\r\n{$site_name} - {$site_url}'),
('en',  'mail.digital', '<p><b>Hello {$fullname},</b></p><p>This email is to inform you that we have sent your digital products.</p><ul><!-- BEGINBLOCK list --><li>{$title}</li><!-- ENDBLOCK --></ul><p>All digital products can be downloaded in your control panel.</p><ol><li>Login using your username &amp; password at our site.</li><li>Go to My Account &gt; My Files.</li><li>All purchased  files are listed there.</li></ol><p>Thank you for doing bussiness with us! :)</p>'),
('en',  'mail.notify',  'Hi,<!-- BEGINIF $sub_type == \'rst\' -->We are pleased to inform you that \"{$title}\" is now available!<!-- ENDIF --><!-- BEGINIF $sub_type == \'pcd\' -->We are pleased to tell you that \"{$title}\" has droped in price! It\'s now only {$price}!<!-- ENDIF -->\r\n\r\nYou can see the product at our site {$site_name}, {$site_url}/detail.php?item_id={$item_id}\r\n\r\n---\r\nYou have received this email because you subscribed for notifications at {$site_name}, {$site_url}\r\nTo manage your subscriptions please go to {$site_url}/account.php and login.'),
('en',  'mail.pending', '<p><b>Hello {$fullname},</b></p><p>This email is to inform you that on {$today}, we set your order status back to pending:</p><p>Order Information<br /><hr />\r\nOrder ID: {$order_id}<br />\r\nOrder date: {$order_date}<br />\r\nTo see your order details, please go to <a href=\"{$site_url}/trx.php?order_id={$order_id}\">{$site_url}/trx.php?order_id={$order_id}</a></p>'),
('en',  'mail.process', '<p><b>Hello {$fullname},</b></p><p>This email is to inform you that on {$today}, we are processing your order as below:</p><p>Order Information<br /><hr />\r\nOrder ID: {$order_id}<br />\r\nOrder date: {$order_date}<br />\r\nTo see your order details, please go to <a href=\"{$site_url}/trx.php?order_id={$order_id}\">{$site_url}/trx.php?order_id={$order_id}</a></p><p>Digital Products<br /><hr />\r\nAll digital products can be downloaded in your control panel.</p><ol><li>Login using your username &amp; password at our site.</li><li>Go to My Account &gt; My Files.</li><li>All purchased  files are listed there.</li></ol>'),
('en',  'mail.ship',  '<p><b>Hello {$fullname},</b></p><p>This email is to inform you that on {$today}, we have shipped your order as below:</p><p>Order Information<br /><hr />\r\nOrder ID: {$order_id}<br />\r\nOrder date: {$order_date}<br />\r\nTo see your order details, please go to <a href=\"{$site_url}/trx.php?order_id={$order_id}\">{$site_url}/trx.php?order_id={$order_id}</a></p><p>Shipping Address<br /><hr />\r\n{$ship_address}</p><p>Digital Products<br /><hr />\r\nAll digital products can be downloaded in your control panel.</p><ol><li>Login using your username &amp; password at our site.</li><li>Go to My Account &gt; My Files.</li><li>All purchased  files are listed there.</li></ol>'),
('en',  'mail.tell_product',  '<p>Hi, <b>{$friend_name}</b>,</p><p>Your friend, {$name} (email: {$email}) thinks that you might be interested in <i>{$title}</i> in our online shop.</p><p>For more information, visit <a href=\"{$site_url}/{$url}\">{$site_url}/{$url}</a>.</p><p style=\"border:solid 1px #999;width:290px; text-align:center; padding:5px\"><b>{$title}</b><br /><a href=\"{$site_url}/{$url}\">{$image}</a><br />{$price}</p><p>Additonally, your friend says:<br />\r\n{$tell_body}</p><p>Best Regards,<br />\r\n{$site_name}<br /><a href=\"{$site_url}\">{$site_url}</a></p>'),
('en',  'mail.tell_us', '<p>Hi, <b>site owner</b>,</p><p>A visitor, {$name} (email: {$email}) sent you a message about a product in your web site of \"{$title}\".</p><p style=\"border:solid 1px #999;width:290px; text-align:center; padding:5px\"><a href=\"{$site_url}/{$url}\"><b>{$title}</b></a><br /><a href=\"{$site_url}/{$url}\">{$image}</a><br />{$details}</p><p>The message is as follow:<br />{$tell_body}</p><p>To answer this message, please contact the visitor directly.</p><p>Best Regards,<br />{$site_name}<br /><a href=\"{$site_url}\">{$site_url}</a></p>'),
('en',  'msg.cancel_not_allow', '<h1>Whoops!</h1><p>Sorry! We can\'t cancel your order at present. Please contact us for more information</p>'),
('en',  'msg.cancel_ok',  '<h1>Order Cancellation Sent!</h1><p>Your request for cancellation has been sent. We will review your request as soon as possible.</p>'),
('en',  'msg.coupon_err', '<h1>Invalid Coupon Code!</h1><p>Invalid coupon code! It may already have expired, been claimed or it could be an incorrect coupon code altogether!</p>'),
('en',  'msg.coupon_ok',  '<h1>Gift Coupon!</h1><p>%1$s</p>'),
('en',  'msg.courier_not_set',  '<h1>Failed!</h1><p>You have entered an unrecognized city, or we do not cover the city which you have just entered.</p>'),
('en',  'msg.internal_error', '<h1>Internal Error</h1><p><p>%1$s</p><p>Please contact site administrator!</p></p>'),
('en',  'msg.item_id_not_found',  '<h1>Product Not Found</h1><p>Product is not availble or no longer available!</p>'),
('en',  'msg.not_queued', '<h1>Unable to Cancel the Order!</h1><p>Current order is no longer queued. You cannot cancel it.</p>'),
('en',  'msg.no_file',  '<h1>File Not Found!</h1><p>File does not exist, or not yours. Please contact us for more information.</p>'),
('en',  'msg.no_item',  '<h1>No items to Display</h1><p>Your query doesn\'t return anything. Please try again.</p>'),
('en',  'msg.no_item_in_cart',  '<h1>Unable to Continue!</h1><p>There are no items in your shopping cart!</p>'),
('en',  'msg.no_stock', '<h1>Out of Stock</h1><p></p>'),
('en',  'msg.order_id_not_found', '<h1>Order ID Not Found</h1><p>Order ID can not be found or is no longer available!</p>'),
('en',  'msg.order_id_null',  '<h1>Order ID Not Set</h1><p>To check your order status, please input an order ID.</p>'),
('en',  'msg.payment_not_selected', '<h1>Checkout Failed!</h1><p>You have not chosen a method of payment. Please return to the previous page and try again</p>'),
('en',  'msg.shipper_not_selected', '<h1>Whoops!</h1><p>You have not chosen a shipping method. Please return to the previous page and try again.</p>'),
('en',  'msg.sub_type_err', '<h1>Unknown Subscription Method!</h1><p>Please contact us for more information</p>'),
('en',  'msg.tax_info', '<h1>Tax Settings</h1><p>To set tax, go to Country/State/City administration.<br />There you can set tax based on a specific country, county / state or even city!</p>');

TRUNCATE TABLE `__PREFIX__menu_item`;
INSERT INTO `__PREFIX__menu_item` (`idx`, `menu_id`, `menu_parent`, `menu_item`, `menu_url`, `menu_permalink`, `menu_order`, `ref_idx`) VALUES
(1, 1,  0,  'Home', '__SITE__/index.php', '', 100,  0),
(4, 2,  0,  'Contact Us', '__SITE__/contact.php', '', 100,  0),
(5, 2,  0,  'Site Map', '__SITE__/sitemap.php', '', 110,  0),
(7, 2,  0,  'Tell a Friend',  '__SITE__/tell.php',  '', 120,  0),
(8, 3,  0,  'Privacy Policy', '2',  '', 100,  0),
(9, 3,  0,  'Terms &amp; Conditions', '7',  '', 110,  0),
(10,  3,  0,  'Powered by qEngine', '8',  '', 130,  0),
(11,  3,  0,  'FAQ',  '3',  '', 120,  0),
(67,  1,  0, 'Shop',  '#', '', 110,  0),
(68,  1,  67, '#',  '[[sm:product]]', '', 120,  0);


TRUNCATE TABLE `__PREFIX__menu_set`;
INSERT INTO `__PREFIX__menu_set` (`idx`, `menu_id`, `menu_title`, `menu_preset`, `menu_class`, `menu_notes`, `menu_cache`, `menu_locked`, `max_depth`, `ref_idx`) VALUES
(1, 'main_menu',  'Main Menu',  'bsnav',  '', 'Main menu, usually located at the top of the page.', '<ul id=\"qmenu_main_menu\" class=\"nav navbar-nav\">\n <li><a href=\"__SITE__/index.php\">Home</a></li>\n <li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\">Shop <span class=\"caret\"></span></a>  <ul class=\"dropdown-menu\">\n    <li><a href=\"[[sm:product]]\">#</a></li>\n </ul>\n</li>\n</ul>\n', '0',  1,  0),
(2, 'footer_menu',  'Footer Menu',  'list_1', '', 'Footer menu, usually located at the end of the page.', '<ul id=\"qmenu_footer_menu\" class=\"list_1\">\n <li><a href=\"__SITE__/contact.php\">Contact Us</a></li>\n  <li><a href=\"__SITE__/sitemap.php\">Site Map</a></li>\n  <li><a href=\"__SITE__/tell.php\">Tell a Friend</a></li>\n</ul>\n',  '0',  1,  0),
(3, 'page_menu',  'Page Menu',  'list_1', '', 'Menu linking to some important, but not that important pages.',  '<ul id=\"qmenu_page_menu\" class=\"list_1\">\n <li><a href=\"__SITE__/page.php?pid=2\">Privacy Policy</a></li>\n <li><a href=\"__SITE__/page.php?pid=7\">Terms & Conditions</a></li>\n <li><a href=\"__SITE__/page.php?pid=3\">FAQ</a></li>\n  <li><a href=\"__SITE__/page.php?pid=8\">Powered by qEngine</a></li>\n</ul>\n',  '0',  1,  0),
(7, 'product',  'Product Menu', 'bsnav',  '', 'Container for product category menu. Do NOT remove!',  '', '1',  0,  0),
(8, 'product_cf', 'Product cf', '', '', 'Container for product custom field ordering. Do NOT remove!',  '',  '1',  1,  0);


INSERT INTO `__PREFIX__module` (`mod_id`, `mod_type`, `mod_name`, `mod_desc`, `mod_version`, `mod_css`, `mod_js`, `mod_enabled`) VALUES
('ce_core', 'general',  'CE Core Module', 'This is a multipurpose module for Cart Engine. This module contains support for product feature, custom field, product option and sub product.', '2.0.0',  '', '', '1'),
('pay_bank',  'payment',  'Bank Wire Transfer', 'A payment gateway for Bank Wire Transfer.',  '2.0.0',  '', '', '1'),
('pay_cheque',  'payment',  'Cheque', 'A payment gateway for By Cheque.', '2.0.0',  '', '', '1'),
('pay_cod', 'payment',  'Cash on Delivery', 'A payment gateway for Cash on Delivery.',  '2.0.0',  '', '', '1'),
('pay_paypal',  'payment',  'PayPal', 'A payment gateway for PayPal (IPN). Also a documentation on creating your own payment gateway.', '2.0.0',  '', '', '1'),
('ship_cod',  'shipping', 'Cash on Delivery (Shipping Module)', 'A shipping gateway for Cash on Delivery (best combined with COD payment module).', '2.0.0',  '', '', '1'),
('ship_free', 'shipping', 'Free Shipping',  'A shipping gateway for Free Shipping.',  '2.0.0',  '', '', '1'),
('ship_item', 'shipping', 'Per Item', 'A shipping gateway for Per Item Shipping.',  '2.0.0',  '', '', '1'),
('ship_percent',  'shipping', 'Percentage', 'A shipping gateway for Percentage of Purchased Total.',  '2.0.0',  '', '', '1'),
('ship_pickup', 'shipping', 'Pickup', 'A shipping gateway for Store Pickup.', '2.0.0',  '', '', '1'),
('ship_weight', 'shipping', 'By Weight (manual calculation)', 'A really simple shipping gateway for By Weight, need to manually enter rates in configuration screen.',  '2.0.0',  '', '', '1');


DROP TABLE IF EXISTS `__PREFIX__orders`;
CREATE TABLE `__PREFIX__orders` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` varchar(80) NOT NULL DEFAULT '',
  `item_id` int(10) unsigned NOT NULL DEFAULT '0',
  `qty` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `timeadd` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`idx`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Temporary order, later moved to order_final';


DROP TABLE IF EXISTS `__PREFIX__order_final`;
CREATE TABLE `__PREFIX__order_final` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` varchar(80) NOT NULL DEFAULT '',
  `cat_id` int(10) unsigned NOT NULL DEFAULT '0',
  `item_id` int(10) unsigned NOT NULL DEFAULT '0',
  `title` varchar(255) NOT NULL DEFAULT '',
  `weight` float NOT NULL DEFAULT '0',
  `price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `qty` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `order_id` varchar(16) NOT NULL DEFAULT '',
  PRIMARY KEY (`idx`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Final order';


DROP TABLE IF EXISTS `__PREFIX__order_summary`;
CREATE TABLE `__PREFIX__order_summary` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` varchar(16) NOT NULL DEFAULT '',
  `user_id` varchar(80) NOT NULL DEFAULT '',
  `user_email` varchar(255) NOT NULL,
  `order_items` int(10) unsigned NOT NULL,
  `order_weight` float unsigned NOT NULL,
  `order_date` date NOT NULL DEFAULT '0000-00-00',
  `order_total` decimal(10,2) NOT NULL DEFAULT '0.00',
  `order_shipping_fee` decimal(10,2) NOT NULL DEFAULT '0.00',
  `order_payment_fee` decimal(10,2) NOT NULL DEFAULT '0.00',
  `order_tax` decimal(10,2) NOT NULL DEFAULT '0.00',
  `gift_discount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `order_payment` varchar(80) NOT NULL DEFAULT '',
  `order_shipper` varchar(80) NOT NULL DEFAULT '',
  `order_paystat` char(1) NOT NULL DEFAULT 'E',
  `order_status` char(1) NOT NULL DEFAULT 'E',
  `order_shipped` date NOT NULL DEFAULT '0000-00-00',
  `order_delivered` date NOT NULL,
  `order_completed` date NOT NULL,
  `order_cancelled` date NOT NULL,
  `fullname` varchar(255) NOT NULL,
  `bill_address` text NOT NULL,
  `ship_address` text NOT NULL,
  `order_notes` text NOT NULL,
  `xpress_co` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `idx` (`idx`),
  KEY `order_date` (`order_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 PACK_KEYS=0 COMMENT='Order summary';


INSERT INTO `__PREFIX__page` (`group_id`, `cat_id`, `page_id`, `permalink`, `page_image`, `page_date`, `page_time`, `page_unix`, `page_title`, `page_keyword`, `page_body`, `page_author`, `page_related`, `page_allow_comment`, `last_update`, `page_rating`, `page_comment`, `page_list`, `page_hit`, `page_img_tmp`, `page_attachment`, `page_attachment_stat`, `page_download`, `page_pinned`, `page_status`, `page_template`, `page_mode`) VALUES
('GENPG', 1,  5,  'success.php',  '', '2011-11-11', '00:00:00', 1320966000, 'Success',  '', '<p>Thank you for purchasing in our site.</p>\r\n<p>You will be guided to pay your transaction.</p>', '', '', '0',  1510418346, 0.00, 0,  '0',  0,  '', '', 0,  '', '0',  'P',  '', 'html');


DROP TABLE IF EXISTS `__PREFIX__payment_log`;
CREATE TABLE `__PREFIX__payment_log` (
  `log_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `log_time` int(10) unsigned NOT NULL,
  `pay_type` varchar(20) NOT NULL,
  `order_id` varchar(16) NOT NULL,
  `txn_id` varchar(32) NOT NULL,
  `order_total` decimal(10,2) NOT NULL,
  `order_paid` decimal(10,2) NOT NULL,
  `sent_request` text NOT NULL,
  `response` text NOT NULL,
  `payment_status` char(1) NOT NULL,
  `notes` text NOT NULL,
  PRIMARY KEY (`log_id`),
  KEY `order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__permalink` (`idx`, `url`, `target_script`, `target_idx`, `target_param`) VALUES
(12,  'success.php',  'page.php', '5',  '');

DROP TABLE IF EXISTS `__PREFIX__products`;
CREATE TABLE `__PREFIX__products` (
  `cat_id` varchar(12) NOT NULL DEFAULT '',
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `sku` varchar(16) NOT NULL DEFAULT '',
  `add_category` varchar(255) NOT NULL DEFAULT '',
  `permalink` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL DEFAULT '',
  `price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `price_msrp` decimal(10,2) unsigned NOT NULL DEFAULT '0.00',
  `price_qty` varchar(255) NOT NULL,
  `details` text NOT NULL,
  `weight` decimal(5,2) unsigned NOT NULL DEFAULT '0.00',
  `distro` int(10) unsigned NOT NULL,
  `list_date` date NOT NULL DEFAULT '0000-00-00',
  `keywords` varchar(255) NOT NULL DEFAULT '',
  `stock` int(10) unsigned NOT NULL DEFAULT '0',
  `min_buy` int(10) unsigned NOT NULL,
  `max_buy` int(10) unsigned NOT NULL,
  `tax_class` int(10) unsigned NOT NULL DEFAULT '0',
  `see_also` varchar(255) NOT NULL DEFAULT '',
  `sub_product` text NOT NULL,
  `digital_file` varchar(255) NOT NULL,
  `is_call_for_price` enum('0','1') NOT NULL DEFAULT '0',
  `is_invisible` enum('0','1') NOT NULL DEFAULT '0',
  `stat_hits` int(10) unsigned NOT NULL DEFAULT '0',
  `stat_last_hit` date NOT NULL DEFAULT '0000-00-00',
  `stat_purchased` int(10) unsigned NOT NULL,
  `stat_last_purchased` date NOT NULL,
  `smart_search` text NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `cat_id` (`cat_id`),
  KEY `sku` (`sku`),
  KEY `add_category` (`add_category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 PACK_KEYS=0 COMMENT='Product list';

DROP TABLE IF EXISTS `__PREFIX__product_cat`;
CREATE TABLE `__PREFIX__product_cat` (
  `parent_id` int(10) unsigned NOT NULL DEFAULT '0',
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `cat_name` varchar(100) NOT NULL DEFAULT '',
  `cat_details` text NOT NULL,
  `cat_image` varchar(255) NOT NULL DEFAULT '',
  `cat_keywords` varchar(255) NOT NULL,
  `cat_featured` varchar(255) NOT NULL DEFAULT '0',
  `cat_page` varchar(10) NOT NULL,
  `menu_mid` int(10) unsigned NOT NULL,
  `permalink` varchar(255) NOT NULL,
  `subcat_order` varchar(255) NOT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__product_cf_define`;
CREATE TABLE `__PREFIX__product_cf_define` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `cf_category` varchar(255) NOT NULL,
  `cf_title` varchar(255) NOT NULL,
  `cf_type` varchar(10) NOT NULL,
  `cf_option` text NOT NULL,
  `cf_help` varchar(255) NOT NULL,
  `is_searchable` enum('0','1') NOT NULL DEFAULT '0',
  `is_list` enum('0','1') NOT NULL DEFAULT '0',
  `menu_idx` int(10) unsigned NOT NULL,
  `menu_item_id` int(10) unsigned NOT NULL,
  `is_removed` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `__PREFIX__product_cf_value`;
CREATE TABLE `__PREFIX__product_cf_value` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `item_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `item_id` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__qcomment_set` (`group_id`, `comment_mode`, `comment_approval`, `member_only`, `unique_comment`, `comment_helpful`, `comment_on_comment`, `captcha`, `detail`, `mod_id`, `notes`) VALUES
(4, '3',  '1',  '1',  '1',  '1',  '1',  '0',  '1',  'product',  'Products');

ALTER TABLE `__PREFIX__user`
ADD `fullname` varchar(100) NOT NULL DEFAULT '' AFTER `user_notes`,
ADD `bill_address` varchar(255) NOT NULL DEFAULT '',
ADD `bill_address2` varchar(255) NOT NULL DEFAULT '',
ADD `bill_district` varchar(255) NOT NULL,
ADD `bill_city` varchar(255) NOT NULL DEFAULT '',
ADD `bill_state` varchar(80) NOT NULL DEFAULT '',
ADD `bill_country` varchar(80) NOT NULL DEFAULT '',
ADD `bill_zip` varchar(15) NOT NULL DEFAULT '',
ADD `ship_address` varchar(255) NOT NULL,
ADD `ship_address2` varchar(255) NOT NULL,
ADD `ship_district` varchar(255) NOT NULL,
ADD `ship_city` varchar(255) NOT NULL,
ADD `ship_state` varchar(80) NOT NULL,
ADD `ship_country` varchar(80) NOT NULL,
ADD `ship_zip` varchar(15) NOT NULL,
ADD `phone` varchar(20) NOT NULL DEFAULT '',
ADD `user_wish` text NOT NULL;


DROP TABLE IF EXISTS `__PREFIX__user_file`;
CREATE TABLE `__PREFIX__user_file` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` varchar(80) NOT NULL,
  `item_id` int(10) unsigned NOT NULL,
  `order_idx` varchar(16) NOT NULL,
  `total_download` int(10) unsigned NOT NULL,
  `last_download` int(10) unsigned NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `user_id` (`user_id`),
  KEY `item_id` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

